### ISSUE TITLE
Option to not expand link after Favourite?

### ISSUE THREAD

**Issue by matthiasbeyer** [mastodon/mastodon#11335]
I hope the title is descriptive enough.

### Pitch

I would like to have an option to _not_ expand a link after hitting "Favourite".

### Motivation

When I really like a toot, I hit "Favourite" and immediately after that I hit "Boost". Unfortunately, the link in the post will be expanded by hitting "Favourite" and so I click on the link rather than on "Boost".

![Screenshot](https://user-images.githubusercontent.com/427866/61352950-e5654900-a86e-11e9-97ec-354e47926f3a.png)

By having an option to _not_ expand the link section (Pointed to by the arrow in above picture), I would not open the link (again) but actually hit "boost" and thus increase my workflow speed with the UI.

---

Thank you for making this awesome software!

**Comment by mjankowski** [comment]
Last relevant update here is ~6 years old ... going to close this on the assumption that this may have been resolved in more current release. If that's NOT the case on current release (4.3) please reopen with relevants logs/screens/etc.

**Comment by trwnh** [comment]
it still happens, but i’m not sure what we can do here.

the issue is that when you interact with a status whose link preview hasn’t been generated yet, it will generate the link preview and cause a layout shift. this can lead to a misclick.

**Comment by mjankowski** [comment]
In scenarios where we don't have it yet but know we might get it, I wonder if a skeleton/placeholder of the elements might help. May not be pixel perfect but might reduce shuffle.
