### ISSUE TITLE
Report comment screen does not indicate that reports are too long until after submitted.

### ISSUE THREAD

**Issue by davidwolfpaw** [mastodon/mastodon#18787]
### Steps to reproduce the problem

1. As an admin or moderator, open a report
2. Type a note into the report that is longer than 500 characters (for default install max length)
3. Submit the note and see the error that the note is too long

### Expected behaviour

A counter should show how many characters are left to add in a note

### Actual behaviour

There is no counter, and notes that are too long will not submit

### Specifications

Basically this is a feature request/bug about no character counter on the admin side when there is one on the client side.

This is an example of the character counter on the web dashboard:
![Screen Shot 2022-07-08 at 17 13 35](https://user-images.githubusercontent.com/1971070/178087269-5b37c9e6-a49e-4245-bd12-b947210bc257.jpg)

This is a too-long comment being typed on a report note:
![Screen Shot 2022-07-08 at 17 15 07](https://user-images.githubusercontent.com/1971070/178087270-201a9923-1bf0-409b-8d66-97a3dd0c5a6a.jpg)

This is a too-long comment after submission:
![Screen Shot 2022-07-08 at 17 15 46](https://user-images.githubusercontent.com/1971070/178087274-79bab657-675b-45a3-91e0-7f589596817d.jpg)

**Comment by ShadowJonathan** [comment]
It seems the limit is defined here: https://github.com/mastodon/mastodon/blob/main/app/models/report_note.rb#L21

**Comment by ThisIsMissEm** [comment]
I'm not sure if we've a generic "metered text input", but I think it should be possible to add this functionality.

**Comment by ThisIsMissEm** [comment]
This is fixed by #30288

@vmstan could you mark this as resolved, thanks!

**Comment by davidwolfpaw** [comment]
@ThisIsMissEm Apologies, but the request that I had (indicating that the report is too long until after submission) has not been solved in the latest version. 

The request is for character count to be shown while typing, as it does in other parts of the UI. This is because even with 2000 characters, someone could submit a note that goes longer than that. If the note does not succeed, the entire note that they wrote will now be gone, as the page has refreshed and not stored the text that they wrote.

The updates made so far are great! I just wanted to note that it does not solve the problem that I originally mentioned, and would still like to see this update added for moderator support.

![Screenshot 2024-09-11 at 9 27 28 AM](https://github.com/user-attachments/assets/3e20b8d2-56ea-4c14-bf61-be865cdc0b05)
![Screenshot 2024-09-11 at 9 28 04 AM](https://github.com/user-attachments/assets/677af1c8-4790-4fc3-ae8c-54e8972a575c)

**Comment by ThisIsMissEm** [comment]
![image](https://github.com/user-attachments/assets/3ecdcb76-5eac-46f4-89a9-a10802402bde)

> If the note does not succeed, the entire note that they wrote will now be gone, as the page has refreshed and not stored the text that they wrote.

So how did you get to the image above with the error state and the text of the note still present?

Yes, we don't show a JavaScript powered counter for how many characters are used, we don't currently have a generic component for that, I'd rather progressively enhance rather than require javascript for a textarea.

**Comment by davidwolfpaw** [comment]
> So how did you get to the image above with the error state and the text of the note still present?
Apologies, you are correct. I copied the text to re-paste it for the second example but you're right, it was saved in localstorage 😅

**Comment by ThisIsMissEm** [comment]
It's not localstorage, that's the form validation returning back the input value. Whilst yes, we could progressively enhance with remaining character count, it's not as simple as reusing what's in the Web UI
