### ISSUE TITLE
Can't follow from a moved account

### ISSUE THREAD

**Issue by naught101** [mastodon/mastodon#19621]
### Steps to reproduce the problem

1. I have an account on mastodon.social
2. I have an account on aus.social, which is redirected to my mastodon.social account
3. I am logged in to both
4. I visit a new_user on https://aus.social/@new_user
5. I press "follow"
6. I am redirected to https://aus.social/auth/edit, and there is no way to follow the account

### Expected behaviour

at step 6, I should be redirected to https://mastodon.social/@new_user@aus.social

### Actual behaviour

I get sent to the auth page on aus.social

### Detailed description

This follow redirect should be an inherrent part of the account redirect

Even if there is a good reason to send me to the auth page on aus.social, at the very least there should be a banner saying:

> If you want to follow @new_user from your redirected account, please visit https://mastodon.social/@new_user@aus.social

But it would be even nicer if I could trigger a follow on mastodon.social directly from aus.social, as this would make finding and following users on that server much faster and more enjoyable.

### Specifications

N/A

**Comment by naught101** [comment]
I should add that it is particularly useful to be logged in to my redirect account on aus.social, because it allows me to browse the network of people with similar interests on that server (I'm australian, but I don't want a second account).

**Comment by naught101** [comment]
Also this addon doesn't work because of this bug, I think?

https://github.com/rugk/mastodon-simplified-federation

**Comment by ClearlyClaire** [comment]
Thanks for the report!

It took my a while to understand what was going on, so I'll try to sum up the issue again: you are visiting an account on an instance which you have moved from, but are still logged into. When you try to follow that account, instead of that happening (as it would if you were logged into a non-moved account), or the remote follow flow kicking up (as would happen if you were not logged in at all), it redirects you to `/auth/edit`, which is pretty much the only page available to logged-in moved accounts.

With the recent redesign (not deployed on your instance), the remote follow flow has changed, and so has general logged-out navigation. I'm not sure how the experience of logged-in-but-moved-accounts is affected, but I'm pretty sure it needs special consideration either way. This will require more investigation.

**Comment by ClearlyClaire** [comment]
The current situation when you are logged in but with a disabled/moved account, after the redesign, is:
- you can access profile pages and posts
- it loads the WebUI using your own settings, including for instance using the advanced layout if you have configured that
- most API requests fail
- you are not presented with a follow button at all
- trying to interact with posts raises an API error

Overall, the easiest way might be to behave as if you were logged out.

**Comment by ClearlyClaire** [comment]
Should be addressed by #19753 (in a change unrelated to the main subject of this PR) and #19773. As far as I know, aus.social is now using those changes, so you can test them and reopen the issue if it isn't satisfactory.

**Comment by naught101** [comment]
Um... The behaviour is different now, I think, but still not good. It no longer takes me to the auth page, but if I'm logged in to aus.social, then going to a user's page that I don't follow and clicking follow shows me the "Sign in or copy the account url page":

![image](https://user-images.githubusercontent.com/167164/200744181-85e690cf-f8b4-4e72-84b5-6511fdbd8ede.png)

The instance knows me, and knows that I have a working redirect, so it should redirect me to http://mastodon.social/@new_user@aus.social directly, or at least with a "would you like to be redirected" modal.

**Comment by naught101** [comment]
I don't think that I have permissions to reopen this issue.
