### ISSUE TITLE
Filters don't apply to auto-refreshed posts

### ISSUE THREAD

**Issue by ivanvector** [mastodon/mastodon#20373]
### Steps to reproduce the problem

1. Create a keyword filter (Preferences > Filters)
2. Load any feed page, and wait for an automatic refresh with a post containing the filtered keyword

### Expected behaviour

The post should be hidden behind the "Filtered: <filter title> Show anyway" banner

### Actual behaviour

The post with the filtered keyword displays as any other post

### Detailed description

The keyword filter function seems to only apply to posts that are visible when a feed is loaded for the first time. If the feed automatically refreshes, new posts containing the keyword which should be filtered are instead displayed as though the filter does not exist. If the page is manually reloaded, the affected posts will then be filtered but any new posts after reloading will not.

### Specifications

Instance is running Mastodon v4.0.0rc1
Observed in Firefox 106.0.5 (64-bit) on Windows 11 Home 22H2

**Comment by afontenot** [comment]
Most likely this is this issue, which the devs have already fixed: https://github.com/mastodon/mastodon/issues/19977 We're just waiting on the next version of Mastodon to be released at this point.

**Comment by ClearlyClaire** [comment]
Fixed in 4.0.0rc3 by #19963!

**Comment by afontenot** [comment]
@ClearlyClaire I appear to still see this behavior on 4.0.0rc3 (mastodon.social). I made a simple filter blocking the word "the". It seems to work when I refresh the page on the public timeline (I see a bunch of blocked posts right away), but then as the new posts load in none of them are blocked.

Actually to be more specific if I scroll *down* the timeline I can get a few more posts to load, and all those seem to be filtered. It's new posts that are loading automatically that are not filtered.

**Comment by ClearlyClaire** [comment]
That's weird, I'm unable to replicate the issue.

**Comment by afontenot** [comment]
@ClearlyClaire thanks for checking, I'm not sure how I can help. Here's a screenshot of my filter that isn't working.

![Screenshot_20221113_035500](https://user-images.githubusercontent.com/3870410/201520427-a169e15f-f937-4c5b-a2ab-9df5aeacdec1.png)

I was tinkering with the hide CW settings, so it's possible I got them into a weird state maybe? I set them back to the defaults (hide CW, hide media).

**Comment by ClearlyClaire** [comment]
Note that you have to reload the web app for filter changes to take effect. Otherwise I don't really know what may be happening, I'll have another look.

**Comment by afontenot** [comment]
Thanks! Not sure if "reload" means just refreshing the page, hard refresh (shift f5) or closing all Mastodon tabs and reopening them. I've done a hard refresh and I still see the issue with the word "the" on both the federated and local timelines on mastodon.social. Haven't tried closing everything / deleting cache / web workers etc.

**Comment by ClearlyClaire** [comment]
For that purpose, just refreshing the page should be enough. I can actually reproduce this on mastodon.social, just not on my personal deployment. I'll keep investigating!

**Comment by ClearlyClaire** [comment]
I have found why I was not able to reproduce the issue: I was testing with an account which I was following, which meant the client got the correct filter result from the Home timeline, and applied it correctly to the public timeline as well. But the code responsible for filtering public and local timelines is indeed broken, gonna fix that soon.

**Comment by ivanvector** [comment]
Seems to be working as expected now with release v4.0.0

**Comment by afontenot** [comment]
Agreed, I haven't seen any problems with this yet.
