### ISSUE TITLE
Remove search from about page

### ISSUE THREAD

**Issue by ryliejamesthomas** [mastodon/mastodon#20930]
### Pitch

Remove search link.

### Motivation

I keep my instance pretty locked-down. Authorised fetched, not public timeline viewing, no user directory, etc. I was surprised to see that there's now a search form on the landing page for visitors who aren't signed in. I don't want visitors to be able to search the Fediverse from my instance.

**Comment by ryliejamesthomas** [comment]
Yep form works.

I just noticed that if I click on a tag from the search result I also get the tag feed, which I thought used to be disabled.

**Comment by joenepraat** [comment]
This is not a suggestion, but a security issue.

**Comment by joenepraat** [comment]
Anyone has a trick to remove it via CSS from the landing page? How does not anybody raised a red flag during development about this major security flaw!? Do we really need to gimmick the security flaws from Twitter?

**Comment by ClearlyClaire** [comment]
Some issues were raised privately and somewhat addressed in #19326 by restricting search to exact matches or 5-characters minimum and disallowing pagination

**Comment by joenepraat** [comment]
> Some issues were raised privately and somewhat addressed in #19326 by restricting search to exact matches or 5-characters minimum and disallowing pagination

Thank you for your reply @ClearlyClaire. Still is still not enough of course. There really should be an option to remove that search bar all together.

**Comment by AstroProfundis** [comment]
Same for me here, the API is actually working for anonymous users, and there are also some more APIs like that. Making a locked instance able to be browsed by any random visitor and breaks the meaning of setting "Public Timeline Preview" disabled. It's different from public timeline preview, but actually more disturbing as it literally can search.

Setting `DISALLOW_UNAUTHENTICATED_API_ACCESS=true` along with `AUTHORIZED_FETCH=true` makes those APIs not accessible, but then causes multiple 401 error messages on the webpages like `/about` and `/explore`.

See #20777 for the related issue.

**Comment by connorshea** [comment]
I probably can't resolve this myself since I'm not familiar enough with the Mastodon codebase to add new admin settings/major changes, but @ClearlyClaire what would the preferred solution be for the mastodon devs here?

- Add a setting that admins can enable that would disable the search endpoint entirely if you're not auth'd
- Automatically disable the search endpoint for un-auth'd users if the instance has "authorized fetches" enabled
- Something else?

**Comment by ShadowJonathan** [comment]
This is not an difference on opinion on how to structure the about/home page, this is a massive information security leak if any agent is allowed to query your homeserver for local users, this could be used to evade authenticated fetch blocks, this is non-negotiably bad, how was this included without enable/disable options for the v4 release???

**Comment by nemobis** [comment]
Related: https://github.com/mastodon/mastodon/issues/22620
