### ISSUE TITLE
Subpaths of /api/v1/streaming do not redirect when a base URL is configured

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#23383]
### Steps to reproduce the problem

1. set `STREAMING_API_BASE_URL` to a subdomain
2. access `/api/v1/streaming/health`

A 404 response is returned, it should be a 301 to the correct URL, like `/api/v1/streaming`

### Expected behaviour

URLs should redirect

### Actual behaviour

URLs are 404

### Detailed description

This is due to this: https://github.com/mastodon/mastodon/blob/main/config/routes.rb#L473

Only the main path is redirected, not the subpaths

### Specifications

Mastodon 4.0.2

**Comment by renchap** [comment]
This is causing issue with some clients when a server changes its streaming URL, see https://oisaur.com/@dimillian@mastodon.social/109801141138814526

**Comment by ClearlyClaire** [comment]
Isn't this a reverse-proxy configuration issue? The Mastodon code itself doesn't do much regarding `STREAMING_API_BASE_URL`

**Comment by Ciantic** [comment]
Quiet simply, this stopped working: https://mastodon.social/api/v1/streaming/health and other subpaths.

**Comment by renchap** [comment]
> Isn't this a reverse-proxy configuration issue? The Mastodon code itself doesn't do much regarding `STREAMING_API_BASE_URL`

It redirects ` api/v1/streaming/health` (in `API::StreamingController`). I think it should not only redirect the base path, but all paths in this prefix, so apps can follow the redirect when the server admin changes the setting.

**Comment by Ciantic** [comment]
This is now fixed, redirect works to https://streaming.mastodon.social/api/v1/streaming/health

**Comment by ClearlyClaire** [comment]
Oh sorry, we *do* redirect in Mastodon itself, I missed that. That happens in `Api::V1::StreamingController`

**Comment by gomarcus** [comment]
The problem persists. The server currently responds to requests to "https://mastodon.social/api/v1/streaming/health" with 404. no forwarding.

HTTP/2 404 Not Found
content-type: text/html; charset=utf-8
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 0
permissions-policy: interest-cohort=()
referrer-policy: same-origin
cache-control: no-cache
content-security-policy: base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://mastodon.social; img-src 'self' https: data: blob: https://mastodon.social; style-src 'self' https://mastodon.social 'nonce-MbJyRRpLffwf1qYkUuEm9A=='; media-src 'self' https: data: https://mastodon.social; frame-src 'self' https:; manifest-src 'self' https://mastodon.social; form-action 'self'; connect-src 'self' data: blob: https://mastodon.social https://files.mastodon.social wss://streaming.mastodon.social; script-src 'self' https://mastodon.social 'wasm-unsafe-eval'; child-src 'self' blob: https://mastodon.social; worker-src 'self' blob: https://mastodon.social
set-cookie: ...
 SameSite=Lax; secure
x-request-id: c4abd52f95e37debf47e65f9665cb5fa
x-runtime: 0.031114
accept-ranges: bytes
via: 1.1 varnish, 1.1 varnish
date: Wed, 01 Mar 2023 19:27:25 GMT
x-served-by: cache-fra-eddf8230048-FRA, cache-hhn-etou8220078-HHN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1677698845.478291,VS0,VE311
vary: Origin
strict-transport-security: max-age=31557600
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
X-Firefox-Spdy: h2

**Comment by mehrvarz** [comment]
My app makes use of /api/v1/streaming/user. It currently does not work with mastodon.social. It does still work with all other instances I have tried. The following may explain why:

curl https://journa.host/api/v1/streaming/user
```
{"error":"Error: Access token does not cover required scopes"}`
```

curl https://mstdn.social/api/v1/streaming/user
```
{"error":"Error: Access token does not cover required scopes"}
```

curl https://mastodon.social/api/v1/streaming/user
```
<!DOCTYPE html>
<html lang='en'>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta charset='utf-8'>
<title>The page you are looking for isn&#39;t here.
...
```

journa.host and mstdn.social return "Error: Access token does not cover required scopes". Without an access token, this is the correct behavior.

But mastodon.social returns 404.

I get the same behavior whether I use curl or open the links in a browser (or in my app).

**Comment by mehrvarz** [comment]
> @mehrvarz your app show not assume the location of the streaming endpoint, but get it from the `instance` endpoint (key: `configuration.url.streaming`).

I checked that using the actual endpoint does indeed solve my problem. Thank you! I was not yet able to find info on how to retrieve the endpoint URL (or configuration) from a remote instance.

**Comment by mehrvarz** [comment]
https://mastodon.social/api/v1/streaming is being redirected to https://streaming.mastodon.social/api/v1/streaming 👍

But https://mastodon.social/api/v1/streaming/user is still giving 404. Is this the desired behavior?

**Comment by renchap** [comment]
This PR has not been released yet.

It will be up on mastodon.social once the next Mastodon version is released and deployed here, and have the behaviour you describe.
