### ISSUE TITLE
4.1 image edit feature does not allow editing the focus point

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#23533]
### Steps to reproduce the problem

On my test account, I made a post with an image. I did not set a caption or focus point.

https://mastodon.social/@mcc_test_tusky/109847032654473817

Afterward, I clicked "Edit" on the post, edited the image, and set a caption and a focus point at the top of the image. When I saved the image and Saved Changes the post, nothing visually changed on screen (image did not refocus). After reloading I could confirm that the post now had a caption but that the focus was still in the center of the image.

I clicked "Edit" on the post again. The focus point was still set in the middle of the image. I moved the focus point to the bottom of the image. I saved the image and Saved Changes the post. As of this moment, looking at my feed, the image has a caption as expected but the focus point is still in the center.

### Expected behaviour

EITHER the focus point should be set correctly when set in the edit image dialog (and ideally the change should be visible immediately upon clicking "Save Changes"), OR the edit image dialog should not offer the ability to change focus point.

### Actual behaviour

Focus point UI was presented, but as described above did nothing.

### Specifications

mastodon dot social just now so v4.1.0rc3. non-advanced UI.
chrome 108.0.5359.125 64-bit on Windows 10. No adblock or other extensions installed.

**Comment by mcclure** [comment]
Even weirder: I tested again with a beta version of Android mobile app "Tusky". Changing the focus point in Tusky (IE, using the external API) **did** work. Despite this I am still unable to edit a focus point in the web client.

**Comment by ClearlyClaire** [comment]
Thanks for the report! Found the issue, addressed by #23566

**Comment by mcclure** [comment]
mastodon.social is now saying it has v4.1.0 but this bug is still occurring
