### ISSUE TITLE
Preview cards not loading after updating Mastodon to v4.1.1.

### ISSUE THREAD

**Issue by mimikun** [mastodon/mastodon#24177]
### Steps to reproduce the problem

1. Access to https://mstdn.mimikun.jp
2. Log in
3. Reload the page(click F5)

### Expected behaviour

Image is loaded

### Actual behaviour

Image is not loaded

#### Screenshot: 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/13450321/226340842-1490ba04-4c0f-4823-881c-7aeca944cf56.png">

#### Full error log:
(Very long)

[mstdn.mimikun.jp-1679315534871.log](https://github.com/mastodon/mastodon/files/11017865/mstdn.mimikun.jp-1679315534871.log)

#### My .env.production

Never been edited in 5 years.

```txt
# Service dependencies
# You may set REDIS_URL instead for more advanced options
# You may also set REDIS_NAMESPACE to share Redis between multiple Mastodon servers
REDIS_HOST=redis
REDIS_PORT=6379
# You may set DATABASE_URL instead for more advanced options
DB_HOST=db
DB_USER=postgres
DB_NAME=postgres
DB_PASS=
DB_PORT=5432

# Federation
# Note: Changing LOCAL_DOMAIN or LOCAL_HTTPS at a later time will cause unwanted side effects.
# LOCAL_DOMAIN should *NOT* contain the protocol part of the domain e.g https://example.com.
LOCAL_DOMAIN=mstdn.mimikun.jp
LOCAL_HTTPS=true

# Use this only if you need to run mastodon on a different domain than the one used for federation.
# You can read more about this option on https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md
# DO *NOT* USE THIS UNLESS YOU KNOW *EXACTLY* WHAT YOU ARE DOING.
# WEB_DOMAIN=mastodon.example.com

# Use this if you want to have several aliases handler@example1.com
# handler@example2.com etc. for the same user. LOCAL_DOMAIN should not
# be added. Comma separated values
# ALTERNATE_DOMAINS=example1.com,example2.com

# Application secrets
# Generate each with the `RAILS_ENV=production bundle exec rake secret` task (`docker-compose run --rm web rake secret` if you use docker compose)
SECRET_KEY_BASE=XXXX_XXXX_XXXX
OTP_SECRET=XXXX_XXXX_XXXX

# VAPID keys (used for push notifications
# You can generate the keys using the following command (first is the private key, second is the public one)
# You should only generate this once per instance. If you later decide to change it, all push subscription will
# be invalidated, requiring the users to access the website again to resubscribe.
#
# Generate with `RAILS_ENV=production bundle exec rake mastodon:webpush:generate_vapid_key` task (`docker-compose run --rm web rake mastodon:webpush:generate_vapid_key` if you use docker compose)
#
# For more information visit https://rossta.net/blog/using-the-web-push-api-with-vapid.html
VAPID_PRIVATE_KEY=XXXX_XXXX_XXXX
VAPID_PUBLIC_KEY=XXXX_XXXX_XXXX

# Registrations
# Single user mode will disable registrations and redirect frontpage to the first profile
# SINGLE_USER_MODE=true
# Prevent registrations with following e-mail domains
# EMAIL_DOMAIN_BLACKLIST=example1.com|example2.de|etc
# Only allow registrations with the following e-mail domains
# EMAIL_DOMAIN_WHITELIST=example1.com|example2.de|etc

# Optionally change default language
DEFAULT_LOCALE=ja

# E-mail configuration
# Note: Mailgun and SparkPost (https://sparkpo.st/smtp) each have good free tiers
# If you want to use an SMTP server without authentication (e.g local Postfix relay)
# then set SMTP_AUTH_METHOD and SMTP_OPENSSL_VERIFY_MODE to 'none' and
# *comment* SMTP_LOGIN and SMTP_PASSWORD (leaving them blank is not enough).
##SMTP_SERVER=smtp.mailgun.org
##SMTP_PORT=587
##SMTP_LOGIN=hoge@example.com
##SMTP_PASSWORD=XXXX_XXXX_XXXX
##SMTP_FROM_ADDRESS=hoge@example.com
##SMTP_DOMAIN=mimikun.jp # defaults to LOCAL_DOMAIN
#SMTP_DELIVERY_METHOD=smtp # delivery method can also be sendmail
##SMTP_AUTH_METHOD=plain
#SMTP_CA_FILE=/etc/ssl/certs/ca-certificates.crt
##SMTP_OPENSSL_VERIFY_MODE=none
##SMTP_ENABLE_STARTTLS_AUTO=true
#SMTP_TLS=true
# ConoHa Mail Server Settings
# SMTP_SERVER=hoge.example.com
# SMTP_PORT=587
# SMTP_LOGIN=hoge@example.com
# SMTP_PASSWORD=XXXX_XXXX_XXXX
# SMTP_FROM_ADDRESS=hoge@example.com
# SMTP_AUTH_METHOD=plain
# SMTP_OPENSSL_VERIFY_MODE=none

# Mailgun Server Settings
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_LOGIN=hoge@example.com
SMTP_PASSWORD=XXXX_XXXX_XXXX
SMTP_FROM_ADDRESS=hoge@example.com
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none

# Optional user upload path and URL (images, avatars). Default is :rails_root/public/system. If you set this variable, you are responsible for making your HTTP server (eg. nginx) serve these files.
# PAPERCLIP_ROOT_PATH=/var/lib/mastodon/public-system
# PAPERCLIP_ROOT_URL=/system

# Optional asset host for multi-server setups
# CDN_HOST=https://assets.example.com

# S3 (optional)
S3_ENABLED=true
S3_BUCKET=mstdn.mimikun.jp
AWS_ACCESS_KEY_ID=XXXX_XXXX_XXXX
AWS_SECRET_ACCESS_KEY=XXXX_XXXX_XXXX
S3_REGION=ap-northeast-1
S3_PROTOCOL=https
S3_ENDPOINT=https://s3-ap-northeast-1.amazonaws.com
# S3_HOSTNAME=192.168.1.123:9000

# S3 (Minio Config (optional) Please check Minio instance for details)
# S3_ENABLED=true
# S3_BUCKET=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# S3_REGION=
# S3_PROTOCOL=https
# S3_HOSTNAME=
# S3_ENDPOINT=
# S3_SIGNATURE_VERSION=

# Swift (optional)
# SWIFT_ENABLED=true
# SWIFT_USERNAME=
# For Keystone V3, the value for SWIFT_TENANT should be the project name
# SWIFT_TENANT=
# SWIFT_PASSWORD=
# Keystone V2 and V3 URLs are supported. Use a V3 URL if possible to avoid
# issues with token rate-limiting during high load.
# SWIFT_AUTH_URL=
# SWIFT_CONTAINER=
# SWIFT_OBJECT_URL=
# SWIFT_REGION=
# Defaults to 'default'
# SWIFT_DOMAIN_NAME=
# Defaults to 60 seconds. Set to 0 to disable
# SWIFT_CACHE_TTL=

# Optional alias for S3 if you want to use Cloudfront or Cloudflare in front
# S3_CLOUDFRONT_HOST=

# Streaming API integration
# STREAMING_API_BASE_URL=

# Advanced settings
# If you need to use pgBouncer, you need to disable prepared statements:
# PREPARED_STATEMENTS=false

# Cluster number setting for streaming API server.
# If you comment out following line, cluster number will be `numOfCpuCores - 1`.
STREAMING_CLUSTER_NUM=1

# Docker mastodon user
# If you use Docker, you may want to assign UID/GID manually.
# UID=1000
# GID=1000
# GITHUB_REPOSITORY

GITHUB_REPOSITORY=mimikun/mastodon
```

#### My nginx config

```txt
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
  listen 80;
  listen [::]:80;
  server_name mstdn.mimikun.jp;
  root /home/mastodon/mastodon/public;
  # Useful for Let's Encrypt
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name mstdn.mimikun.jp;

  ssl_protocols TLSv1.2;
  ssl_ciphers HIGH:!MEDIUM:!LOW:!aNULL:!NULL:!SHA;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;

  ssl_certificate     /etc/letsencrypt/live/mstdn.mimikun.jp/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mstdn.mimikun.jp/privkey.pem;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  root /home/mastodon/mastodon/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  add_header Strict-Transport-Security "max-age=31536000";

  # CSP 

  #add_header Content-Security-Policy "style-src 'self' https://mstdn.mimikun.jp 'nonce-tM3t2dWilkteCGTbrc9kIw==' 'unsafe-inline'; script-src 'self'; object-src 'self' https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp; img-src data: https: blob:; media-src data: https:; font-src 'self' data:; connect-src 'self' wss://mstdn.mimikun.jp blob:; upgrade-insecure-requests";

  #add_header X-Content-Security-Policy "style-src 'self' 'unsafe-inline'; script-src 'self'; object-src 'self' https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp; img-src data: https: blob:; media-src data: https:; font-src 'self' data:; connect-src 'self' wss://mstdn.mimikun.jp blob:; upgrade-insecure-requests";

  #add_header X-WebKit-CSP "style-src 'self' 'unsafe-inline'; script-src 'self' blob: https://mstdn.mimikun.jp; object-src 'self' https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp; img-src data: https: blob:; media-src data: https:; font-src 'self' data:; connect-src 'self' wss://mstdn.mimikun.jp blob:; upgrade-insecure-requests";

  add_header 'Access-Control-Allow-Origin'  '*';

  location / {
    try_files $uri @proxy;
  }

  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000";
    try_files $uri @proxy;
  }

  location /sw.js {
    add_header Cache-Control "public, max-age=0";
    add_header Strict-Transport-Security "max-age=31536000";
    try_files $uri @proxy;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://127.0.0.1:3000;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;
    add_header Strict-Transport-Security "max-age=31536000";

    tcp_nodelay on;
  }

  location /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";

    proxy_pass http://127.0.0.1:4000;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }

  error_page 500 501 502 503 504 /500.html;
}
```
### Specifications

Mastodon: (https://github.com/mastodon/mastodon/commit/94cbd808b5b3e7999c7e77dc724b7e8c9dd2bdec)
Vivaldi: 5.7.2921.63 (Stable channel) (64-bit) 
Using Cloudflare, Amazon S3

**Comment by quartje** [comment]
We experience the same issue. Images that are in the browser cache are not loaded. When doing a hard refresh (SHIFT-F5), the images show up. When restarting the browser, the images are gone again.
We save the images remotely using swift storage, on a different domain.

The browser console shows: 
`A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with Error: no-response`

**Comment by syui** [comment]
I have the same problem with volumes

**Comment by nichu42** [comment]
Is this about preview images from links only? Then this issue is probably a duplicate of #24118.
Or does this happen with uploaded media as well?

**Comment by syui** [comment]
also uploaded media

**Comment by mimikun** [comment]
@nichu42 
No, this does not occur with uploaded media.
This issue occurs only when logging in with a web browser.
It can be viewed successfully using mobile apps such as Ivory or the official Mastodon app. (probably accessed via API).

**Comment by syui** [comment]
In my case the url of the image not logged in was 404

**Comment by ClearlyClaire** [comment]
@mimikun and @syui's problems seem to be different.

I would be very surprised if @mimikun's problem were caused by the upgrade from v4.1.0 to v4.1.1 since I don't think anything has changed in regards to how object storage is used for media attachments, nor regarding caching strategies.

But the logged-in VS logged-out behaviors seem to point to an issue with the service worker. However, the error logs are full of CSP violations, which should not happen in Mastodon itself. Do you have custom changes?

@syui's is your install new or did the issue start with v4.1.1? How is your server set up?

**Comment by syui** [comment]
issue ... 4.1.1
ok ... downgrade 4.1.0
i server setup : fly.io -> docker -> mount/volume -> image(media)
$ ls /mastodon/public/system/xxx.jpg ... ok
but error 404

**Comment by mimikun** [comment]
@ClearlyClaire 
My custom details are as follows:
https://github.com/mastodon/mastodon/compare/v4.1.1... .mimikun:mastodon:fix-media-error-challenge?diff=split

- Retain deleted Keybase integrations
- Change media file size limit

nginx, .env.production settings are as described at the beginning of this issue.

**Comment by nativehyun** [comment]
Same issue here.
Instance: https://renkontu.com
Issue: Images are not loading after login.
Server configuration: Docker, Cloudflare, Backblaze B2 for object storage.

**Comment by ClearlyClaire** [comment]
> My custom details are as follows: [v4.1.1...mimikun:mastodon:fix-media-error-challenge](https://github.com/mastodon/mastodon/compare/v4.1.1...mimikun:mastodon:fix-media-error-challenge)
> 
>     * Retain deleted Keybase integrations
> 
>     * Change media file size limit
> 
> 
> nginx, .env.production settings are as described at the beginning of this issue.

@mimikun Sorry, there appear to be a very significant amount of changes, I am not sure we can support that.

**Comment by ClearlyClaire** [comment]
@syui thank you for the information.

@dziq @nativehyun as I understand, at least two different issues have been described in this thread. Can you clarify the following points?
- is the issue about preview cards only, or all (or a random subset of) media files?
- does it still occur if you are logged out?
- using the “Network” tab of your browser's dev tools, can you see whether the failure to load the media is because of a 404, or some other issue?

**Comment by nativehyun** [comment]
@ClearlyClaire Thanks for your reply.

1. It happens on preview cards only, not stored media.
2. It does not happens when I logged out.
3. It seems "NS_ERROR_INTERCEPTION_FAILED" error.

**Comment by ClearlyClaire** [comment]
@dziq skimming over https://sleeplessbeastie.eu/2022/05/02/how-to-take-advantage-of-docker-to-install-mastodon/, the setup around media uploads seems a little tricky, and the `.env.production` file containing `RAILS_SERVE_STATIC_FILES=false` was actually interpreted by v4.1.0 and before as telling Rails to serve static files, while it now instructs Rails not to do so.

This means that if something in your configuration (wrong mount path, wrong permissions on the mounted volume, …) prevents `nginx` from serving the files directly, Mastodon/Rails would have served them anyway before 4.1.1, but stopped in 4.1.1. To return to the previous behavior, you can set `RAILS_SERVE_STATIC_FILES=true`.

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire Thanks for your reply.
> 
>     1. It happens on preview cards only, not stored media.
> 
>     2. It does not happens when I logged out.
> 
>     3. It seems "NS_ERROR_INTERCEPTION_FAILED" error.

Thanks, that does seem to be similar to what @mimikun is describing. Can you see any any other error in your browser's console? What browser are you using? Does CTRL+F5 help? Does this also occur with v4.1.0? (downgrading should be safe)

**Comment by nativehyun** [comment]
> > @ClearlyClaire Thanks for your reply.
> > ```
> > 1. It happens on preview cards only, not stored media.
> > 
> > 2. It does not happens when I logged out.
> > 
> > 3. It seems "NS_ERROR_INTERCEPTION_FAILED" error.
> > ```
> 
> Thanks, that does seem to be similar to what @mimikun is describing. Can you see any any other error in your browser's console? What browser are you using? Does CTRL+F5 help? Does this also occur with v4.1.0? (downgrading should be safe)

Thanks for your reply. I can see following error in browser console:
`Failed to read 'https://contents.renkontu.com/file/renkontu/custom_emojis/images/000/009/732/original/17b4f200d02dbe7e.png'. ServiceWorker returns 'Error: no-response :: [{"url":"https://contents.renkontu.com/file/renkontu/custom_emojis/images/000/009/732/original/17b4f200d02dbe7e.png","error A returned promise was sent to FetchEvent.respondWith() with ":{}}]'.`

Clear cache is not helping. It doesn't happened on v4.1.0. I use latest version of Safari and Firefox on Mac(Apple Silicon)

**Comment by dziq** [comment]
> @dziq skimming over https://sleeplessbeastie.eu/2022/05/02/how-to-take-advantage-of-docker-to-install-mastodon/, the setup around media uploads seems a little tricky, and the `.env.production` file containing `RAILS_SERVE_STATIC_FILES=false` was actually interpreted by v4.1.0 and before as telling Rails to serve static files, while it now instructs Rails not to do so.
> 
> This means that if something in your configuration (wrong mount path, wrong permissions on the mounted volume, …) prevents `nginx` from serving the files directly, Mastodon/Rails would have served them anyway before 4.1.1, but stopped in 4.1.1. To return to the previous behavior, you can set `RAILS_SERVE_STATIC_FILES=true`.

Thank you. Setting RAILS_SERVE_STATIC_FILES=true solves problem.

**Comment by ClearlyClaire** [comment]
@dziq good! I have updated the 4.1.1 release notes to point out the change of behavior in `RAILS_SERVE_STATIC_FILES` to hopefully help with other people running into this. As a side note, depending on your setup and what you want from it, you may want to investigate serving the files directly from nginx, as this should offer better performances.

@nativehyun thanks! This is indeed the service worker not working as it should, but I don't understand why, especially since it should not have changed between v4.1.0 and v4.1.0. Does this occur with all your browsers? Do you have any local changes?

**Comment by mimikun** [comment]
@ClearlyClaire 
Thanks for your reply. 
Are you saying that there are too many changes to narrow down the cause?
If so, I will remove the changes and get closer to vanilla mastodon.

**Comment by SerenadeX** [comment]
I am seeing something similar to this, I have a B2 bucket set up for media cache.  When I load up the instance in a web browser on Safari (16.4), I get broken images on all media, emoji, previews, and avatars.  In Firefox I have no problems.  In native apps, I have no problems.  If I look at the console of Safari and try and open one of the URLs in it, it loads in a separate window without a problem.  My environment is as follows:

```
      RAILS_ENV: 'production'                                                      
      LOCAL_DOMAIN: '${MASTODON_DOMAIN}'                                           
      REDIS_HOST: 'redis' # name of the redis container                            
      DB_HOST: 'db' # name of the database container                               
      DB_NAME: '${MASTODON_POSTGRES_DATABASE}'                                     
      DB_USER: '${MASTODON_POSTGRES_USERNAME}'                                     
      DB_PASS: '${MASTODON_POSTGRES_PASSWORD}'                                     
      SECRET_KEY_BASE: '${MASTODON_SECRET_KEY_BASE}'                               
      OTP_SECRET: '${MASTODON_OTP_SECRET}'                                         
      SMTP_SERVER: '${SMTP_SERVER}'                                                
      SMTP_PORT: '${SMTP_PORT}'                                                    
      SMTP_LOGIN: '${SMTP_LOGIN}'                                                  
      SMTP_PASSWORD: '${SMTP_PASSWORD}'                                            
      SMTP_FROM_ADDRESS: '${SMTP_FROM_ADDRESS}'                                    
      SMTP_DOMAIN: '${SMTP_DOMAIN}'                                                
      SMTP_OPENSSL_VERIFY_MODE: '${SMTP_OPENSSL_VERIFY_MODE}'                      
      ES_ENABLED: true                                                             
      ES_HOST: *******
      S3_ENABLED: true                                                             
      S3_BUCKET: *******                                                      
      S3_REGION: US-West                                                           
      S3_HOSTNAME: s3.us-west-001.backblazeb2.com                                  
      S3_ENDPOINT: https://s3.us-west-001.backblazeb2.com                          
      AWS_ACCESS_KEY_ID: *******                                 
      AWS_SECRET_ACCESS_KEY: *******                       
      S3_ALIAS_HOST: f001.backblazeb2.com*****
      RAILS_SERVE_STATIC_FILES: true    
```
I obfuscated anything I felt was unnecessary or secure.  As you can see I tried setting `RAILS_SERVE_STATIC_FILES` to true, but it did not change anything.  I am also running v4.1.1

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire
Thanks for your reply.
Are you saying that there are too many changes to narrow down the cause?

Yes.

> If so, I will remove the changes and get closer to vanilla mastodon.

If you end up doing that, please also share browser error logs from that closer-to-vanilla Mastodon version, along with the changes between vanilla Mastodon and your version.

@SerenadeX your issue is unrelated to `RAILS_SERVE_STATIC_FILES`. I'm interested in the errors that show up in Safari's console.

**Comment by SerenadeX** [comment]
For every url that loads Safari logs these three messages:

FetchEvent.respondWith received an error: no-response: no-response :: [{"url":"<url>", "error":{}}]
Cannot load <url>.
Failed to load resource: FetchEvent.respondWith received an error: no-response: no-response :: [{"url":"<url>", "error":{}}]

Strangely enough, if I clear the cache and reload the page, all existing posts with images will load the images without a problem, but new posts will not be able to load the images.

Here is one example request that I did both in Firefox and in Safari.

![Firefox Request](https://user-images.githubusercontent.com/1624085/227582272-4644f077-6835-4f25-b285-8cc25240e32e.png)
![Safari Request](https://user-images.githubusercontent.com/1624085/227582347-a7103ca0-adb4-4c81-82ca-3ab5583befbc.png)

**Comment by mimikun** [comment]
@ClearlyClaire 
Some changes have been removed to bring it closer to vanilla Mastodon.
As a result, the issue of preview cards not showing up has been resolved.
The differences from Mastodon v4.1.0 are as follows:

https://github.com/mastodon/mastodon/compare/v4.1.0...mimikun:mastodon:mimikun/master

**Comment by nativehyun** [comment]
> @ClearlyClaire Some changes have been removed to bring it closer to vanilla Mastodon. As a result, the issue of preview cards not showing up has been resolved. The differences from Mastodon v4.1.0 are as follows:
> 
> [v4.1.0...mimikun:mastodon:mimikun/master](https://github.com/mastodon/mastodon/compare/v4.1.0...mimikun:mastodon:mimikun/master)

Are you using Docker for your instance? I’m using Docker and didn’t changed the image but still happens the issue.

**Comment by mimikun** [comment]
@nativehyun 
Yes, I am using Docker. 
In my case, I had made some changes and removed them and before I knew it, it was fixed.

**Comment by nativehyun** [comment]
I think this issue is related to content security policy. I'can see a CSP error in my Firefox console.

**Comment by ClearlyClaire** [comment]
> I think this issue is related to content security policy. I'can see a CSP error in my Firefox console.

What are those CSP errors?

**Comment by SurplusXoyo** [comment]
> > I think this issue is related to content security policy. I'can see a CSP error in my Firefox console.
> 
> What are those CSP errors?

![20230401132234](https://user-images.githubusercontent.com/48602941/229267472-ba76260a-0201-4ca1-924c-91a606e1fb60.png)

These errors only occur after the user has logged in, and visitors without browser caching can load these third-party resources normally.

**Comment by ledlamp** [comment]
i have same issue, i'm using PAPERCLIP_ROOT_URL with different domain for files

![image](https://user-images.githubusercontent.com/103386533/229323340-9d8a86bb-aab5-4aad-b9e9-c06f66128e80.png)

**Comment by mimikun** [comment]
Exactly one week later, this issue reappeared. ( 1 week ago: https://github.com/mastodon/mastodon/issues/24177#issuecomment-1484010485 )
The error is below.

```txt
Refused to connect to 'https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/cache/preview_cards/images/002/247/365/original/e959588c8db6b817.png' because it violates the document's Content Security Policy.
```

It is a CSP problem.
What should I do?

**Comment by ClearlyClaire** [comment]
> It is a CSP problem. What should I do?

@mimikun do you have any custom change to `config/initializers/content_security_policy.rb`? What is your current value for `S3_ALIAS_HOST`, `S3_CLOUDFRONT_HOST`, and `S3_HOSTNAME`?

**Comment by mimikun** [comment]
@ClearlyClaire 
No changes have been made as confirmed by `compare`.
https://github.com/mastodon/mastodon/compare/main...mimikun:mastodon:mimikun/master

Three values were checked.
I found it commented out or not set.

```shell
$ cat .env.production | grep S3_ALIAS_HOST
$ cat .env.production | grep S3_CLOUDFRONT_HOST
# S3_CLOUDFRONT_HOST=
$ cat .env.production | grep S3_HOSTNAME
# S3_HOSTNAME=192.168.1.123:9000
# S3_HOSTNAME=
```

**Comment by ClearlyClaire** [comment]
Ok so that's the issue: you should have set either `S3_HOSTNAME` or `S3_ALIAS_HOST`. In your case, I think you want `S3_HOSTNAME=s3-ap-northeast-1.amazonaws.com`

**Comment by mimikun** [comment]
@ClearlyClaire 
Thank you.

1. Set a value for S3_HOSTNAME

```shell
$ cat .env.production | grep S3_HOSTNAME
#S3_HOSTNAME=192.168.1.123:9000
S3_HOSTNAME=s3-ap-northeast-1.amazonaws.com
# S3_HOSTNAME=
```

2. sudo docker-compose up -d
3. Clear browser cache
4. Login to my Mastodon

but I get an error.

StrategyHandler.js
```
Refused to connect to 'https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/accounts/avatars/000/000/001/original/2bf2e1b95f1c55b7 .png' because it violates the document's Content Security Policy.
```

**Comment by ClearlyClaire** [comment]
@mimikun since like your reverse proxy has cached the reply with the wrong CSP headers for sw.js

**Comment by nativehyun** [comment]
> @ClearlyClaire Thank you.
> 
> 1. Set a value for S3_HOSTNAME
> 
> ```shell
> $ cat .env.production | grep S3_HOSTNAME
> #S3_HOSTNAME=192.168.1.123:9000
> S3_HOSTNAME=s3-ap-northeast-1.amazonaws.com
> # S3_HOSTNAME=
> ```
> 
>  2. sudo docker-compose up -d
> 3. Clear browser cache
> 4. Login to my Mastodon
> 
> but I get an error.
> 
> StrategyHandler.js
> 
> ```
> Refused to connect to 'https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/accounts/avatars/000/000/001/original/2bf2e1b95f1c55b7 .png' because it violates the document's Content Security Policy.
> ```

I can see same CSP error from my instance. I've set S3_HOSTNAME and S3_ALIAS_HOST.
the difference is I'm using Backblaze B2 and Cloudflare instead Amazon S3.

**Comment by mimikun** [comment]
@ClearlyClaire Does this mean I have to wait until the reverse proxy cache is cleared?

**Comment by ledlamp** [comment]
it's not the reverse proxy it's your browser, you have to try it with a fresh profile (i.e. chrome guest). idk how to reset it

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire Does this mean I have to wait until the reverse proxy cache is cleared?

I'm not sure whether it's nginx or CloudFlare caching the `https://mstdn.mimikun.jp/sw.js` response but it is definitely cached with the wrong header, it has the wrong `connect-src` CSP directive, unlike `https://mstdn.mimikun.jp/sw.js?foo`.

**Comment by mimikun** [comment]
@ClearlyClaire 
1. `sudo rm -rf /var/cache/nginx/*`
2. CloudFlare cache purge (using [Purge Everything](https://developers.cloudflare.com/cache/how-to/purge-cache/#purge-everything) )
3. Browser cache delete
4. Login mstdn.mimikun.jp

```txt
Refused to connect to 'https://s3-ap-northeast-1.amazonaws.com/mstdn.mimikun.jp/cache/preview_cards/images/002/389/722/original/f14a1b0eb04eb9ce.jpeg' because it violates the document's Content Security Policy.
```

How to fix it?
Can we disable the CSP if we want to?

**Comment by mikeelston** [comment]
Same issue.  
Using Backblaze B2, Cloudflare and running mastodon in Docker with https://hub.docker.com/r/tootsuite/mastodon/

**Comment by ClearlyClaire** [comment]
@mimikun I don't know :/ the incorrect reply seems to still be cached by either nginx or CloudFlare, and I'm unsure why or what you could do to solve it

@mikeelston do you have any CSP error in the browser console? What is your domain name?

**Comment by mikeelston** [comment]
@ClearlyClaire here is a video and screenshots of my issue.  
I did resolve it by switching to Bunny CDN.  which isnt really a solution.  

What im unsure is...  
With Cloudflare i had my `S3_ALIAS_HOST` set to `files.kzoo.to/file/kalamazoo-social`  this is per backblaze instructions for setting up CDN to a public B2 bucket.  
So is the issue the path as part of the host name.  
Bunny acts as a more common CDN where you dont have that extra path.

https://user-images.githubusercontent.com/640349/230608852-8ef0fad5-93ec-4dcb-877a-ba282f6c8332.mp4
<img width="1388" alt="Screenshot 2023-04-06 at 9 35 50 AM" src="https://user-images.githubusercontent.com/640349/230608873-dea3a17a-3f8b-43e3-ad29-fce1a3dd1441.png">
<img width="492" alt="Screenshot 2023-04-06 at 9 46 39 AM" src="https://user-images.githubusercontent.com/640349/230608875-295e8e2a-5d86-45da-800a-cdbd7dcdc015.png">

**Comment by ClearlyClaire** [comment]
@mikeelston oh, right, `S3_ALIAS_HOST` is supposed to be a bare domain, not an URL, and not include any path. When you use `S3_ALIAS_HOST`, the bucket name should be implied by the domain name.

@mimikun is this still occurring for you? It seems the incorrect response for `sw.js` is not in your server-side cache anymore, so unless there's something wrong with the client-side cache, I think it should work now.

@nativehyun glad you solved your issue but I don't understand how switching from nginx to Apache would have changed anything :/

**Comment by mimikun** [comment]
@ClearlyClaire 
Thanks for the reply.

The following commits are add:
https://github.com/mimikun/mastodon/commit/2aec4e2373e34d5eaba9c43d80375a6b9d79983c
https://github.com/mimikun/mastodon/commit/976c215cb0b2b743e0a4b336c553ef99a5ea06dd

One week has passed.
No recurrence Preview-card issue.

I think the issue is solved.
(I have no way to verify that it is really not a problem.)

**Comment by ClearlyClaire** [comment]
I'm closing this issue as different people actually had different issues and it seems all of them have been fixed. If your issue is not fixed, please open a new issue with details about your configuration, and feel free to tag me to bring it to my attention.

> [mimikun@2aec4e2](https://github.com/mimikun/mastodon/commit/2aec4e2373e34d5eaba9c43d80375a6b9d79983c)

This shouldn't need a change in the code, only in your config: you are expected to have either `S3_HOSTNAME` or `S3_ALIAS_HOST` set. `S3_ALIAS_DOMAIN` is not a defined environment variable in Mastodon, and I am not sure what benefit it would have over `S3_ALIAS_HOST`.

> [mimikun@976c215](https://github.com/mimikun/mastodon/commit/976c215cb0b2b743e0a4b336c553ef99a5ea06dd)

This is redundant with the `else` case a few lines down.

**Comment by juanbits** [comment]
@mimikun 

i had today the same problem updating from v4.0.2 to v4.1.2 and migrating the instance to another server.

i fix my nginx file from:
root /home/mypath/opt/mastodon/;

to:
root /home/mypath/opt/mastodon/web/;

You can include the mentioned line in the policy:
location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {

before:
try_files $uri @proxy;

if you not using ES3 or external service to save the uploaded files

for ex:
```
  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000";
    root /home/mypath/opt/mastodon/web/;
    try_files $uri @proxy;
  }
```

**Comment by mimikun** [comment]
@juanbits 

Thanks for your comment.
Could you use code blocks to write it in a way that is easier to read?
It is very confusing.

**Comment by xrain0610** [comment]
`ruby
Rails.application.config.content_security_policy do |p|
  p.base_uri        :none
  p.default_src     :none
  p.frame_ancestors :none
  p.font_src        :self, assets_host
  p.img_src         :self, :https, :data, :blob, assets_host
  p.style_src       :self, assets_host
  p.media_src       :self, :https, :data, assets_host
  p.frame_src       :self, :https
  p.manifest_src    :self, assets_host
  p.form_action     :self
  p.child_src       :self, :blob, assets_host
  p.worker_src      :self, :blob, assets_host

  if Rails.env.development?
    webpacker_urls = %w(ws http).map { |protocol| "#{protocol}#{Webpacker.dev_server.https? ? 's' : ''}://#{Webpacker.dev_server.host_with_port}" }

    p.connect_src :self, :data, :blob, assets_host, media_host, Rails.configuration.x.streaming_api_base_url, *webpacker_urls
    p.script_src  :self, :unsafe_inline, :unsafe_eval, assets_host
  else
    p.connect_src :self, :data, :blob, assets_host, media_host, Rails.configuration.x.streaming_api_base_url
    p.script_src  :self, assets_host, "'wasm-unsafe-eval'"
  end
end`

the img-src and media_src not include the S3_Alias_HOST, is the problem here?

**Comment by ClearlyClaire** [comment]
I stand corrected on `S3_ALIAS_HOST` not always being a bare domain. The environment variable name reflects the name of the underlying library, but confusingly, this can include a path component.

This means people having a path component in there probably have a legit configuration that results in incorrect CSP headers.

This should be addressed in #25273

**Comment by dcmarimba** [comment]
I fixed this, because the cache dir in my web root wasn't part of the nginx options. 

So, before:

`location ~ ^/(system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000" always;
    root /var/opt/mastodon/web/;
    try_files $uri @proxy;
  }`

After:

`location ~ ^/(system/accounts/avatars|system/media_attachments/files|system/cache) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000" always;
    root /var/opt/mastodon/web/;
    try_files $uri @proxy;
  }`

I just noticed that all the images were 404'ing and I could *see* that they were there. Resolved it straight away.

**Comment by trankten** [comment]
Good morning @ClearlyClaire. 

I've started experiencing the same problem at MastoRock.com for no apparent reason. No changes have been made and the images are publicly accesible through the media proxy. 

Currently running 4.1.6

**Comment by ClearlyClaire** [comment]
Do you have an example? Also MastoRock.com seems to have several local modifications that might or might not be related. Finally, what's the server's configuration for media attachments?

**Comment by trankten** [comment]
This is the .env.production config which has been working perfectly fine.

![imagen](https://github.com/mastodon/mastodon/assets/86560527/7d9b08ee-f20c-4af8-9d34-13e526a49dd8)

And this is the nginx config file for the media endpoint.

![imagen](https://github.com/mastodon/mastodon/assets/86560527/7c20a9eb-0baf-4363-a8a5-e96cb69a3850)

Right now the images are accesible, as you can see here my avatar: 
https://media.mastorock.com/rock/cache/accounts/avatars/110/498/482/282/703/434/original/5eecd0dd740fb7d8.jpg

However I'm not sure why browser loads return this (Images load fine in mobile application).
![imagen](https://github.com/mastodon/mastodon/assets/86560527/34c94702-2676-4361-84b0-2148bd6b367b)

**Comment by ClearlyClaire** [comment]
Do you have errors in your browser's console (not the network tab)?

**Comment by trankten** [comment]
> Do you have errors in your browser's console (not the network tab)?

Yeah I've just noticed. I didn't check the console before, my bad.

![imagen](https://github.com/mastodon/mastodon/assets/86560527/4ee5b32f-43db-4eef-8373-aaea4f851851)

I'm not sure if it's worth pointing that https://Mast.Lat instance has the same configuration and code of MastoRock (only different .env files and CSS) and the images work properly.

**Comment by trankten** [comment]
Nope, no updates that I can remember, only versioned branch updates. 

Just in any case I've just pulled the source code again for v4.1.6, put the .env.production file for the instance with no other modifications, and rebuilt the Docker containers but the problem persists. I've also purged browser and CF cache.

**Comment by cloutier** [comment]
I am also getting the same problem on 4.1.7 using OVH block storage. Images work fine from within mobile clients (tested Ivory and IceCube) though

**Comment by ClearlyClaire** [comment]
The symptoms really look like `sw.js` (the service worker) being served with a Content-Security-Policy that forbids fetching from your CDN domain, but for mastorocks.com at least, the CSP I get when requesting `sw.js` should be fine and allow access to media.mastorocks.com, so I don't understand what could be happening except for a cached response with an invalid Content-Security-Policy, but you seem to have cleared caches.

> I am also getting the same problem on 4.1.7 using OVH block storage. Images work fine from within mobile clients (tested Ivory and IceCube) though

The symptoms sound similar, although I cannot investigate more without the domain name, but you should have a look at the CSP for `/sw.js` and check that `connect-src` allows for your CDN.

**Comment by trankten** [comment]
Hello @ClearlyClaire, for some reason which I don't know I got it fixed after setting S3_REGION in the .env file yesterday. Not sure if the same applies to other people but that's the only change I've performed.

![imagen](https://github.com/mastodon/mastodon/assets/86560527/d40334d9-77d5-4b49-b1fd-ccd273ece457)

**Comment by cloutier** [comment]
Your intuition about the security policy seems to be right. Here is the csp for my server hosted at r.town:
```
Content-Security-Policy
	base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://r.town/; img-src 'self' https: data: blob: https://r.town/; style-src 'self' https://r.town/ 'nonce-iixllkvE4m35wmTuDbRCAQ=='; media-src 'self' https: data: https://r.town/; frame-src 'self' https:; manifest-src 'self' https://r.town/; form-action 'self'; connect-src 'self' data: blob: https://r.town/ https://r.town/ wss://r.town; script-src 'self' https://r.town/ 'wasm-unsafe-eval'; child-src 'self' blob: https://r.town/; worker-src 'self' blob: https://r.town/
```

And my S3 config:
```
S3_ENABLED=true
S3_BUCKET=rtownfiles
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
S3_ENDPOINT=https://s3.bhs.io.cloud.ovh.net
S3_REGION=bhs
S3_ALIAS_HOST=rtownfiles.s3.bhs.io.cloud.ovh.net
S3_HOSTNAME=rtownfiles.s3.bhs.io.cloud.ovh.net
S3_OVERRIDE_PATH_STYLE=true
```

I would have though that the S3_ALIAS_HOST would be added automatically to the CSP, is there something else I must do to add it?

**Comment by ClearlyClaire** [comment]
It definitely should be there in `connect-src` at least, and I do see it here if I visit r.town… so not sure what's happening here

**Comment by eallion** [comment]
same

**Comment by cdzombak** [comment]
I just spent way too much time on this.

`sudo rm -rf /var/cache/nginx/*` **does not always work**, since (as in my case) regular users cannot list `/var/cache/nginx`, and the regular user's shell — not `root`'s — is evaluating the `*`.

Instead, use `sudo -i` to open an interactive terminal as `root`, **and then** run `rm /var/cache/nginx/* -rf`.

**Comment by radaiming** [comment]
> I've just noticed that going into the Debugger tools -> Applicatio and clicking on "Unregister" the service worker, the images started showing again.
> 
> ![imagen](https://user-images.githubusercontent.com/86560527/264078832-49987ead-88bb-4383-a827-c35e890408a3.png)
> 
> But a browser restart made the images to be gone again.

Whenever I change `S3_ALIAS_HOST` to a new domain, `NS_ERROR_INTERCEPTION_FAILED` happens and all images failed to load, I used to waste hours to debug, finally found a workaround. To keep image loading after refresh/restart, I simply delete CSP header, usability > security.

**Comment by grahhnt** [comment]
This can be solved by setting CORS headers to allow your main domain to modify the request

eg `files.grants.cafe` sends `Access-Control-Allow-Origin: https://grants.cafe` to allow [grants.cafe](https://grants.cafe)'s service worker to intercept the request

ensure the header includes `https://` otherwise it will not work
