### ISSUE TITLE
After 4.1.5 upgrade cannot hit /admin/dashboard page

### ISSUE THREAD

**Issue by colinstu12** [mastodon/mastodon#26157]
### Steps to reproduce the problem

1. Upgrade from 4.1.4 to 4.1.5 following provided steps from Github
2. Navigate to <mastodomain>/admin/dashboard, after 130 seconds you are presented with the "We're sorry, but something went wrong on our end." message

(Environment: Ubuntu 22.0.4 LTS in VM)

### Expected behaviour

The page should've loaded like normal

### Actual behaviour

after 130 seconds you are presented with the "We're sorry, but something went wrong on our end." message

### Detailed description

I've ran journalctl -u mastodon-web and the only thing that gets logged is that page getting hit, a HTTP status of 200 (makes sense, since the page DOES load but something wrong must be happening in the background, and it lists the long load time as well. 

I *am* able to hit all of the other "Admin" pages just fine (thankfully I had the URLs in history), only the Dashboard is experiencing this. 

Services have been restarted per the guide, as well as restarting the whole VM, no change. Not running out of memory nor disk space. 

Not seeing any other issues anywhere in the settings nor in using the rest of the normal frontend. 

### Mastodon instance

birdbutt.com

### Mastodon version

v4.1.5

### Browser name and version

Chrome 114

### Operating system

macOS 13.4.1

**Comment by renchap** [comment]
We suspect this is fixed by https://github.com/mastodon/mastodon/pull/26116

By any chance, do you have Elasticsearch configured, but not working? This should come from an HTTP timeout, and on this page we check 2 things: that we can reach out to your configured ES server, and that your S3 storage config is correct

**Comment by tchristiansen** [comment]
> By any chance, do you have Elasticsearch configured, but not working?

Elasticsearch and S3 storage are both running as expected. Still unable to reach `/admin/dashboard`

**Comment by renchap** [comment]
Thanks. Any chance you can try to apply this patch and see if it solves the issue: https://github.com/mastodon/mastodon/pull/26116/files ?

**Comment by colinstu12** [comment]
> Elasticsearch

I was not even aware this was an option! Sounds neat, may implement that later but no I do not have this configured nor enabled (or even started / partially configured). 
I also do not use S3 storage (or any cloud storage). 

What are the steps to apply the patch? (sorry). I did some searching and some posts mention that it should end in .patch but not seeing that in the linked commit so just want to 100% ensure the right steps are followed and not going to make it worse. 
Thank!

**Comment by ClearlyClaire** [comment]
You could get the patch from https://patch-diff.githubusercontent.com/raw/mastodon/mastodon/pull/26116.patch and apply it with `git am 26116.patch`

Are you able to e.g. do `curl https://your-server/about` from your server itself? Was the dashboard slow to show up before 4.1.5?

**Comment by colinstu12** [comment]
> You could get the patch from https://patch-diff.githubusercontent.com/raw/mastodon/mastodon/pull/26116.patch and apply it with `git am 26116.patch`
> 
> Are you able to e.g. do `curl https://your-server/about` from your server itself? Was the dashboard slow to show up before 4.1.5?

Yes the dashboard has always been slow to load for me. I've searched for that before but never saw it get reported so I figured it was normal. Never 130 seconds long however, I don't have an exact timing prior to 4.1.5 but it sure felt like 15-45 seconds before. It's been like that for awhile. 

Huh, for some reason when I run curl from server itself for my about page, it just sits there and nothing happens, a new blank line appears and nothing else. When I run it from a remote system I get output immediately.

**Comment by ClearlyClaire** [comment]
Alright, that sounds like the media privacy self-check would not work and take 10 seconds before timing out before 4.1.5, and the timeout logic was broken by 4.1.5, meaning it would exceed those 10 seconds and instead time out the whole rendering

**Comment by tchristiansen** [comment]
> Thanks. Any chance you can try to apply this patch and see if it solves the issue: https://github.com/mastodon/mastodon/pull/26116/files ?

This patch fixes the issue for me.

**Comment by colinstu12** [comment]
This patch fixes the issue for me as well. And crazily enough it loads way faster than it ever did before as well somehow (only 4s). Doesn't make sense?

**Comment by tchristiansen** [comment]
> This means that your web server is most probably not able to reach out your media storage, which is needed for our media storage configuration check.

What kind of configuration check is performed? My S3 Storage Server (minIO) works well:
- All files are displayed as expected
- Sidekiq throws no errors
- Users are able to upload files

**Comment by renchap** [comment]
It checks that you do not have file listing enabled on your setup, causing possibly private files (user exports) to be available to anybody.

I am not sure you were hitting the same issue that @colinstu12 but I suspect this might be it. Something from the admin panel was contacting a remote server synchronously and timing out, this can be either your media host or your ES server.

You can try running `curl` from a shell in your Puma host/container, targeting a file on your S3 storage, and see if it times out.

**Comment by colinstu12** [comment]
Figured it out, had to add a local A record to my router (host override). Once I did that the curl command returns the desired/expected result. The admin dashboard also now loads instantaneously.  Should've set that up from the start. 
I suppose the patch was not necessary for me then, that still does not explain the reduced load time post-patch but pre-DNS/router config fix. 
Is there any issue with leaving the patch in place? I'm assuming any future version pulls will overwrite the patch?

**Comment by tchristiansen** [comment]
> Are you able to e.g. do `curl https://your-server/about` from your server itself?

Im not able to reach `curl https://your-server/about` neither. Due to my firewall settings this is no surprise. Do I have to add a local DNS entry to resolve it? If so it should be documented somewhere in the default installation guide.

> It checks that you do not have file listing enabled on your setup, causing possibly private files (user exports) to be available to anybody.

I can access files when I request the server by its IP-Address: `S3_ENDPOINT=http://<IP-ADDRESS>:9000`

Is it possible that the checks are performed against the `S3_HOSTNAME=files.mydomain.com` and not against the `S3_ENDPOINT=http://<IP-ADDRESS>:9000` which are different in my setup.

**Comment by renchap** [comment]
The code for this is here: https://github.com/mastodon/mastodon/blob/6781dc6462b0511a2d3e6e08c965b7006ffd3331/app/lib/admin/system_check/media_privacy_check.rb#L29

It checks both our media domain and directly your S3 host, as both could be scanned.

We have a documentation on how to configure MinIO for correct permissions if needed: https://docs.joinmastodon.org/admin/optional/object-storage/

**Comment by tchristiansen** [comment]
https://github.com/mastodon/mastodon/blob/6781dc6462b0511a2d3e6e08c965b7006ffd3331/app/lib/admin/system_check/media_privacy_check.rb#L55-L56

It seems like my suggestion was right and the check is performed against the `S3_HOSTNAME`. Which will not work in my configuration:
Mastodon and minIO running on separate machines behind a Firewall. Both accepting requests on port 443 from the outside via their hostname (`mydomain.com` and `files.mydomain.com`). Communication behind the firewall addresses the service directly via IP address. Here is my configuration:
```
S3_ENABLED=true
S3_BUCKET=myBucketName
AWS_ACCESS_KEY_ID=secretKey
AWS_SECRET_ACCESS_KEY=secretAccessKey
S3_PROTOCOL=https
S3_ENDPOINT=http://10.200.1.5:9000
S3_HOSTNAME=files.mydomain.com
```
Setting the `S3_ENDPOINT` working well so far (With exception of these checks).

Changing Line 56 to:
`urls_to_check << "#{s3_protocol}://#{s3_endpoint}/#{bucket_name}/"`

fixes the Problem for me as well. (Without the patch #26116)

As the S3 settings are not really documented (https://docs.joinmastodon.org/admin/config/#s3) im not 100% sure if I use the  `S3_ENDPOINT` right. But I guess it may take into account for that check (like the `S3_ALIAS_HOST` is: `if s3_host_alias.present?`).

Unfortunately im not a ruby developer, so I'm not able to make a proper merge request to solve it.

**Comment by ClearlyClaire** [comment]
@tchristiansen we may want to test against `s3_host_name` *and* `s3_endpoint` as the test is meant to test whether files could be accessed if the proper host names could be guessed… but that would be another issue

The root issue here has been identified, and fixed by https://github.com/mastodon/mastodon/pull/26116

There is an adjacent issue, in that the self-checks can take a while, making the dashboard longer to load. Ideally, this should probably be done asynchronously using some javascript, but that will require quite a few changes.

**Comment by tchristiansen** [comment]
> @tchristiansen we may want to test against `s3_host_name` _and_ `s3_endpoint` as the test is meant to test whether files could be accessed if the proper host names could be guessed… but that would be another issue
> 
> The root issue here has been identified, and fixed by #26116

I startet a new issue to address this: #26191

**Comment by ClearlyClaire** [comment]
Thanks!

**Comment by ClearlyClaire** [comment]
This should have been fixed by 4.1.6, can you confirm?

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire we've been able to reproduce this with an elasticsearch outage causing requests to Admin::DashboardController to hang (along with other ES powered endpoints)

**Comment by mjankowski** [comment]
> [@ClearlyClaire](https://github.com/ClearlyClaire) we've been able to reproduce this with an elasticsearch outage causing requests to Admin::DashboardController to hang (along with other ES powered endpoints)

Running what server version? (and ... replicable?)

**Comment by ThisIsMissEm** [comment]
Various: 4.2.12-hometown-1.1.1, 4.3.1, 4.3.0, etc.

Here's data from Hachyderm, p95 duration is almost always 10-20 seconds. The worst are 95 seconds.

![Image](https://github.com/user-attachments/assets/a7786e67-26c8-4c89-bcb1-ed27cc68dee4)

As you can see, almost all the time of 1m 35s is spent in the database. These queries are slow and put heavy load on the database. We shouldn't be running them every time someone goes to the admin dashboard.

![Image](https://github.com/user-attachments/assets/30558194-dde8-45b7-945d-9f7d643fd86e)

**Comment by ThisIsMissEm** [comment]
In https://github.com/mastodon/mastodon/pull/32948 I do move some of the more expensive queries into a "statistics" dashboard for the instance details page.

**Comment by colinstu12** [comment]
What does the execution plan look like for these queries when experiencing this slowness? What's coming up as high cost?

**Comment by ThisIsMissEm** [comment]
I don't have the actual arguments, but assuming within a single day:

```
EXPLAIN ANALYZE SELECT accounts.domain, count(*) AS value FROM statuses 
INNER JOIN accounts ON accounts.id = statuses.account_id 
WHERE statuses.id BETWEEN 113597271244800000 AND 113602933489664000 
GROUP BY accounts.domain ORDER BY count(*) DESC LIMIT 20;

                                                                                       QUERY PLAN                                                                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=66839.04..66839.09 rows=20 width=22) (actual time=613.877..778.250 rows=20 loops=1)
   ->  Sort  (cost=66839.04..66845.59 rows=2620 width=22) (actual time=613.876..778.248 rows=20 loops=1)
         Sort Key: (count(*)) DESC
         Sort Method: top-N heapsort  Memory: 27kB
         ->  Finalize GroupAggregate  (cost=66105.55..66769.33 rows=2620 width=22) (actual time=609.553..777.784 rows=3945 loops=1)
               Group Key: accounts.domain
               ->  Gather Merge  (cost=66105.55..66716.93 rows=5240 width=22) (actual time=609.547..776.355 rows=8788 loops=1)
                     Workers Planned: 2
                     Workers Launched: 2
                     ->  Sort  (cost=65105.53..65112.08 rows=2620 width=22) (actual time=603.354..603.564 rows=2929 loops=3)
                           Sort Key: accounts.domain
                           Sort Method: quicksort  Memory: 293kB
                           Worker 0:  Sort Method: quicksort  Memory: 284kB
                           Worker 1:  Sort Method: quicksort  Memory: 288kB
                           ->  Partial HashAggregate  (cost=64930.57..64956.77 rows=2620 width=22) (actual time=599.398..599.792 rows=2929 loops=3)
                                 Group Key: accounts.domain
                                 Batches: 1  Memory Usage: 625kB
                                 Worker 0:  Batches: 1  Memory Usage: 625kB
                                 Worker 1:  Batches: 1  Memory Usage: 625kB
                                 ->  Nested Loop  (cost=1.00..64811.03 rows=23908 width=14) (actual time=0.122..578.801 rows=90606 loops=3)
                                       ->  Parallel Index Scan using statuses_pkey on statuses  (cost=0.57..18855.70 rows=23908 width=8) (actual time=0.048..128.205 rows=90606 loops=3)
                                             Index Cond: ((id >= '113597271244800000'::bigint) AND (id <= '113602933489664000'::bigint))
                                       ->  Index Scan using accounts_pkey on accounts  (cost=0.43..1.92 rows=1 width=22) (actual time=0.005..0.005 rows=1 loops=271817)
                                             Index Cond: (id = statuses.account_id)
 Planning Time: 0.441 ms
 Execution Time: 778.311 ms

```

1 week period:

```
EXPLAIN ANALYZE SELECT accounts.domain, count(*) AS value FROM statuses 
INNER JOIN accounts ON accounts.id = statuses.account_id 
WHERE statuses.id BETWEEN 113557635072000000 AND 113602933489664000 
GROUP BY accounts.domain ORDER BY count(*) DESC LIMIT 20;

                                                                                         QUERY PLAN                                                                                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=259052.61..259052.66 rows=20 width=22) (actual time=8950.316..9424.048 rows=20 loops=1)
   ->  Sort  (cost=259052.61..259059.16 rows=2620 width=22) (actual time=8934.872..9408.601 rows=20 loops=1)
         Sort Key: (count(*)) DESC
         Sort Method: top-N heapsort  Memory: 27kB
         ->  Finalize GroupAggregate  (cost=257649.47..258982.89 rows=2620 width=22) (actual time=8922.013..9407.726 rows=7427 loops=1)
               Group Key: accounts.domain
               ->  Gather Merge  (cost=257649.47..258904.29 rows=10480 width=22) (actual time=8921.999..9404.447 rows=26813 loops=1)
                     Workers Planned: 4
                     Workers Launched: 4
                     ->  Sort  (cost=256649.42..256655.97 rows=2620 width=22) (actual time=8896.431..8896.922 rows=5363 loops=5)
                           Sort Key: accounts.domain
                           Sort Method: quicksort  Memory: 549kB
                           Worker 0:  Sort Method: quicksort  Memory: 545kB
                           Worker 1:  Sort Method: quicksort  Memory: 544kB
                           Worker 2:  Sort Method: quicksort  Memory: 542kB
                           Worker 3:  Sort Method: quicksort  Memory: 547kB
                           ->  Partial HashAggregate  (cost=256474.46..256500.66 rows=2620 width=22) (actual time=8888.467..8889.155 rows=5363 loops=5)
                                 Group Key: accounts.domain
                                 Batches: 1  Memory Usage: 721kB
                                 Worker 0:  Batches: 1  Memory Usage: 721kB
                                 Worker 1:  Batches: 1  Memory Usage: 721kB
                                 Worker 2:  Batches: 1  Memory Usage: 721kB
                                 Worker 3:  Batches: 1  Memory Usage: 721kB
                                 ->  Nested Loop  (cost=1.01..255715.47 rows=151799 width=14) (actual time=6.208..8758.414 rows=608257 loops=5)
                                       ->  Parallel Index Scan using statuses_pkey on statuses  (cost=0.57..195368.30 rows=151799 width=8) (actual time=0.421..7690.641 rows=608257 loops=5)
                                             Index Cond: ((id >= '113557635072000000'::bigint) AND (id <= '113602933489664000'::bigint))
                                       ->  Memoize  (cost=0.44..1.55 rows=1 width=22) (actual time=0.001..0.001 rows=1 loops=3041284)
                                             Cache Key: statuses.account_id
                                             Cache Mode: logical
                                             Hits: 568874  Misses: 73330  Evictions: 0  Overflows: 0  Memory Usage: 9214kB
                                             Worker 0:  Hits: 523950  Misses: 71020  Evictions: 0  Overflows: 0  Memory Usage: 8924kB
                                             Worker 1:  Hits: 529224  Misses: 71204  Evictions: 0  Overflows: 0  Memory Usage: 8947kB
                                             Worker 2:  Hits: 525998  Misses: 70992  Evictions: 0  Overflows: 0  Memory Usage: 8920kB
                                             Worker 3:  Hits: 535158  Misses: 71534  Evictions: 0  Overflows: 0  Memory Usage: 8987kB
                                             ->  Index Scan using accounts_pkey on accounts  (cost=0.43..1.54 rows=1 width=22) (actual time=0.009..0.009 rows=1 loops=358080)
                                                   Index Cond: (id = statuses.account_id)
 Planning Time: 0.410 ms
 JIT:
   Functions: 89
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 5.042 ms, Inlining 0.000 ms, Optimization 1.965 ms, Emission 42.125 ms, Total 49.132 ms
 Execution Time: 9451.474 ms
```

**Comment by ThisIsMissEm** [comment]
I did recently read that you shouldn't be using `BETWEEN` either: https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_BETWEEN_.28especially_with_timestamps.29

**Comment by ThisIsMissEm** [comment]
From what I can tell, usually the dimensions queries in the admin dashboard are for a single day.

**Comment by ThisIsMissEm** [comment]
So on Hachyderm I just loaded the dashboard, the request was: `{"keys":["servers"],"start_at":"2024-11-06","end_at":"2024-12-05","limit":8}` 

Which resulted in a 504 error with this timing information:

![Image](https://github.com/user-attachments/assets/4dce4ee9-744d-4930-9722-4a1215c58e88)

**Comment by ClearlyClaire** [comment]
Many different things are discussed in this issue, but the last bunch of comments are about a different (though still serious) issue: those expensive SQL queries would not prevent access to `/admin/dashboard`.

**Comment by colinstu12** [comment]
Is there any way to have the whole page load/render at first but lazily load these graphs in later as the query runs and eventually returns results to the graph when the query completes?

**Comment by ClearlyClaire** [comment]
That is the current behavior.

**Comment by mjankowski** [comment]
> Many different things are discussed in this issue, but the last bunch of comments are about a different (though still serious) issue: those expensive SQL queries would not prevent access to `/admin/dashboard`.

Good point! Just to confirm though, we think the S3 and ES related timeout issues that more fully broke the page were solved by linked PR (and remain solved), correct? But the slow query thing filling in those dashboard areas is valid? (and does not break page totally, but can bog down DB w/ long running queries)

**Comment by mjankowski** [comment]
I had interpreted the previous "fixed in 4.1.6" comments and links to https://github.com/mastodon/mastodon/pull/26116/files to suggest that one had resolved the timeout stuff discussed earlier on here, but I did not thoroughly review that idea.

**Comment by ClearlyClaire** [comment]
Oh, yeah, sure. But https://github.com/mastodon/mastodon/issues/26157#issuecomment-2466935686 is very likely to be current, unless I misunderstood @ThisIsMissEm's comment

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire I think what I'm seeing is folks reloading the admin dashboard several times and triggering multiple requests for the domain measures which ultimately takes the database out with too many slow queries such that the regular queries to load the page and check access control fail.

That said though, we do we need a synchronous check against Elasticsearch and similar?

**Comment by vmstan** [comment]
Let's move discussion of the dashboard performance issue to #31014

**Comment by colinstu12** [comment]
Patch from https://github.com/mastodon/mastodon/pull/26116/files fixed this for me. 
I have not seen this issue happen in 4.2.x and later. 
Discussion of dashboard performance issues was moved to https://github.com/mastodon/mastodon/issues/31014
