### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#26587]
### Steps to reproduce the problem

1. Upgrade to v4.2.0-beta2
2. Restart Mastodon services
3. Access any page via web interface
4. "Something went wrong" error

### Expected behaviour

Pages loading just fine

### Actual behaviour

"Something went wrong" error

### Detailed description

After upgrading from `v4.2.0-beta1` to `4.2.0-beta2`, the web interface broke. Any page the users try to load in the frontend results in errors and the browser even freezes quickly. The backend, like `/settings/*`, is fine.

Looking at the browser console, there are errors like these:

- [1. chrome-console-explore-logged-in.txt](https://github.com/mastodon/mastodon/files/12403152/1.chrome-console-explore-logged-in.txt)
- [2. chrome-console-live-feeds-incognito.log](https://github.com/mastodon/mastodon/files/12403154/2.chrome-console-live-feeds-incognito.log)
- [1. firefox-console-live-feeds-incognito.txt](https://github.com/mastodon/mastodon/files/12403153/1.firefox-console-live-feeds-incognito.txt)
- [2. firefox-console-explore-logged-in.txt](https://github.com/mastodon/mastodon/files/12403155/2.firefox-console-explore-logged-in.txt)

This happens with or without `CDN_HOST` being set. Setting the default Mastodon theme doesn't help, and even accessing the server without being logged (like via incognito tab) also results in error when trying to access links like Explore or Live Feeds.

Already tried using commands like `bundle exec rake tmp:cache:clear assets:clean assets:clobber assets:precompile` and deleting or renaming `/home/mastodon/live/public/assets`. Also tried `bundle pristine` and didn't help either.

There's nothing relevant in the output of `journalctl -xf -u mastodon-*`.

### Mastodon instance

bolha.one

### Mastodon version

v4.2.0-beta2

### Browser name and version

Firefox 116.0.3, Chromium 117.0.5924.0

### Operating system

Windows 11

**Comment by ClearlyClaire** [comment]
Do you have any custom change to your server? Do you use browser extensions that could interfere?

**Comment by ClearlyClaire** [comment]
Most of the logs are incomplete or don't point to an accurate location, but one of the traces seem to point to an accurate location:
https://github.com/mastodon/mastodon/blob/facfec1ba36cee27f232ebff90b990933719235a/app/javascript/mastodon/components/status.jsx#L548

@renchap any idea there?

**Comment by renchap** [comment]
It would throw this error if we had `import getHashtagBarForStatus from './hashtag_bar';`, but this is not the case.

I am not sure what is happening here, and I could not reproduce it locally 🤔

**Comment by cadusilva** [comment]
> Do you have any custom change to your server? Do you use browser extensions that could interfere?

At the time of the problem, I ran `git diff` and the only differences were edits to the language and theme files (`pt-BR.yml`, `en.yml`, `themes.yml`) to include the custom themes names. Other than that, there were no custom edits in effect due to `git stash` and `git fetch`.

I also tested using the incognito window, with no add-ons like uBlock Origin or Tampermonkey enabled, and there were those errors anyway.

Due to the severity, making it not possible to use the web interface, I reverted the virtual machine to a previous same-day backup running `v4.2.0-beta1`. But before that, I took a backup of the `v4.2.0-beta2` installation.

**Comment by renchap** [comment]
Can you update to the latest `main` version (which is beta2 with 3 additional commits), and try to run `bundle exec assets:precompile` again?

We merged #26600 which detects circular dependencies issues, and I think this is what is happening here.

I am not sure why it does not happen in CI or on my own instance, but it would help us if you can try it.

**Comment by cadusilva** [comment]
> Can you update to the latest `main` version (which is beta2 with 3 additional commits), and try to run `bundle exec assets:precompile` again?
> 
> We merged #26600 which detects circular dependencies issues, and I think this is what is happening here.
> 
> I am not sure why it does not happen in CI or on my own instance, but it would help us if you can try it.

Hello, I reinstalled `v4.2.0-beta2` from `v4.2.0-beta1` using `git stash; git fetch; git checkout v4.2.0-beta2`. After the procedures, the problem persists:

The "Copy stacktrace to clipboard" while logged in:

```
TypeError: Object(...) is not a function

render@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:893348
Ts@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156665
Cs@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156463
jl@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1199807
_c@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1188012
vc@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187940
bc@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187801
ic@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184608
cc@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184997
Ha@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1125844
ac/<@https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1182545

render (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:893348)
Ts (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156665)
Cs (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156463)
jl (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1199807)
_c (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1188012)
vc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187940)
bc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187801)
ic (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184608)
cc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184997)
Ha (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1125844)
ac/< (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1182545)
```

The error report while in incognito:

```
TypeError: Object(...) is not a function
render (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:893348)
Ts (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156665)
Cs (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156463)
jl (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1199807)
_c (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1188012)
vc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187940)
bc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187801)
ic (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184608)
cc (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184997)
Ha (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1125844)
ac/< (https://static.masto.cdn.bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1182545)
```

The problem also happens with `CDN_HOST` not set.

Logged in:

```
TypeError: Object(...) is not a function

render@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:893348
Ts@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156665
Cs@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1156463
jl@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1199807
_c@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1188012
vc@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187940
bc@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1187801
ic@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184608
cc@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1184997
Ha@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1125844
ac/<@https://bolha.one/packs/js/common-f156b75f0b3915572507.js:2:1182545
```

Incognito:

```
TypeError: Object(...) is not a function
status.get (webpack:///app/javascript/mastodon/components/status.jsx:70:33)
wi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3592:9)
di (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3577:10)
Bc (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1068:2)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5339:57)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5336:6)
Error(p (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5325:19)
Xj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5115:84)
lc.onCommitFiberUnmount (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5136:31)
fa (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1927:89)
d.hasOwnProperty (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4519:386)
```

**Comment by cadusilva** [comment]
> You need to `git checkout main`, not `4.2.0-beta2`, so you can use the new circular dependency webpack plugin I added

Sorry, I missed that. I'll be back soon.

**Comment by cadusilva** [comment]
So, the problem is still here.

After running:

```
$ git checkout main
M       config/locales/en.yml
M       config/locales/pt-BR.yml
M       config/themes.yml
Already on 'main'
Your branch is up to date with 'origin/main'.

$ bundle install; yarn install
$ bundle exec rails assets:clean
$ bundle exec rails assets:clobber
$ bundle exec rails assets:precompile
```

The same error persists after restarting the services:

```
TypeError: Object(...) is not a function

render@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:893353
Ts@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156670
Cs@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156468
jl@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1199812
_c@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1188017
vc@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187945
bc@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187806
ic@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1184613
cc@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1185002
Ha@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1125849
ac/<@https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1182550

render (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:893353)
Ts (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156670)
Cs (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156468)
jl (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1199812)
_c (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1188017)
vc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187945)
bc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187806)
ic (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1184613)
cc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1185002)
Ha (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1125849)
ac/< (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1182550)

TypeError: Object(...) is not a function
render (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:893353)
Ts (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156670)
Cs (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1156468)
jl (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1199812)
_c (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1188017)
vc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187945)
bc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1187806)
ic (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1184613)
cc (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1185002)
Ha (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1125849)
ac/< (https://static.masto.cdn.bolha.one/packs/js/common-9238bc9bb735aa0249d5.js:2:1182550)
```

**Comment by renchap** [comment]
Did `bundle exec rails assets:precompile` output anything?

**Comment by cadusilva** [comment]
So I reverted to the previous backup running `v4.2.0-beta1` and started it all over again. I ran the [commands from previous post](https://github.com/mastodon/mastodon/issues/26587#issuecomment-1688242003), but this time things worked fine.

Just to be sure, I switched branches to `v4.2.0-beta2` one and it also worked fine.

It may be worth noting that one of the things I did differently this time was to check for file ownership, so I ran `chown -R mastodon:mastodon /home/mastodon/live/`.

Here's other outputs from one of the latest executions, while on `main` branch.

Command `git status`:

```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        app/javascript/styles/mastodon-bird-ui-contrast.scss
        app/javascript/styles/mastodon-bird-ui-dark.scss
        app/javascript/styles/mastodon-bird-ui-light.scss
        app/javascript/styles/mastodon-bird-ui/
        app/javascript/styles/tangerineui-purple.scss
        app/javascript/styles/tangerineui-purple/
        app/javascript/styles/tangerineui.scss
        app/javascript/styles/tangerineui/
        bird-ui
        recompile
        update

nothing added to commit but untracked files present (use "git add" to track)
```

Command `bundle install`:

<details>
<summary>Long block of code</summary>

```
Fetching gem metadata from https://rubygems.org/.........
Using rake 13.0.6
Using minitest 5.19.0
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.7.1
Using crass 1.0.6
Using websocket-extensions 0.1.5
Using marcel 1.0.2
Fetching mini_mime 1.1.5
Using concurrent-ruby 1.2.2
Using date 3.3.3
Using timeout 0.4.0
Using jsonapi-renderer 0.2.2
Using public_suffix 5.0.3
Using aes_key_wrap 1.1.0
Using android_key_attestation 0.3.0
Using encryptor 3.0.0
Using attr_required 1.0.1
Using awrence 1.2.1
Using aws-eventstream 1.2.0
Using aws-partitions 1.793.0
Using jmespath 1.6.2
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using multipart-post 2.3.0
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using faraday-retry 1.0.3
Using ruby2_keywords 0.0.5
Using rack 2.2.8
Using bcrypt 3.1.18
Using bindata 2.4.15
Using blurhash 0.1.7
Using msgpack 1.7.1
Using browser 5.3.1
Using redis 4.8.1
Using bundler 2.4.13
Using cbor 0.5.9.6
Using charlock_holmes 0.7.7
Using multi_json 1.15.0
Using elasticsearch-dsl 0.1.10
Using chunky_png 1.4.0
Using climate_control 0.2.0
Using cocoon 1.2.15
Using color_diff 0.1
Using openssl 3.1.0
Using orm_adapter 0.5.0
Using method_source 1.0.0
Using thor 1.2.2
Using zeitwerk 2.6.11
Using rotp 6.2.2
Using unf_ext 0.0.8.2
Using dotenv 2.8.1
Using ed25519 1.3.0
Using excon 0.100.0
Using fast_blank 1.0.1
Using fastimage 2.2.7
Using ffi 1.15.5
Using formatador 0.3.0
Fetching mime-types-data 3.2023.0808
Using connection_pool 2.4.1
Using nio4r 2.5.9
Using ipaddress 0.8.3
Using raabro 1.4.0
Using temple 0.10.2
Using tilt 2.2.0
Using hashie 5.0.0
Using json 2.6.3
Using hiredis 0.6.3
Using hkdf 0.3.0
Using htmlentities 4.3.4
Using http-form_data 2.3.0
Using http_accept_language 2.1.1
Using httpclient 2.8.3
Using rainbow 3.1.1
Using idn-ruby 0.1.5
Using json-canonicalization 0.3.2
Using link_header 0.0.8
Using jwt 2.7.1
Using kaminari-core 1.2.2
Using uri 0.12.2
Using net-ldap 0.18.0
Using oj 3.15.0
Using rexml 3.2.6
Using ox 2.14.17
Using parslet 2.0.0
Using tty-color 0.6.0
Using pg 1.5.3
Using posix-spawn 0.3.15
Using private_address_check 0.5.0
Using redcarpet 3.6.0
Using rqrcode_core 1.2.0
Using ruby-progressbar 1.13.0
Using rubyzip 2.3.2
Using semantic_range 3.0.0
Using tty-cursor 0.7.1
Using tty-screen 0.8.1
Using wisper 2.0.1
Using xorcist 1.1.3
Using i18n 1.14.1
Using tzinfo 2.0.6
Fetching nokogiri 1.15.4 (x86_64-linux)
Using statsd-ruby 1.5.0
Fetching websocket-driver 0.7.6
Installing websocket-driver 0.7.6 with native extensions
Installing mini_mime 1.1.5
Installing mime-types-data 3.2023.0808
Using net-protocol 0.2.1
Using addressable 2.8.4
Using attr_encrypted 4.0.0
Using aws-sigv4 1.6.0
Using faraday-multipart 1.0.4
Using rack-test 2.1.0
Using bootsnap 1.16.0
Using brpoplpush-redis_script 0.1.3
Using elasticsearch-api 7.13.3
Using openssl-signature_algorithm 1.3.0
Using warden 1.2.9
Using unf 0.1.4
Using ffi-compiler 1.0.1
Using terrapin 0.6.0
Using request_store 1.5.1
Using mario-redis-lock 1.2.1
Using rack-protection 3.0.5
Using rack-attack 6.7.0
Using rack-cors 2.0.1
Using rack-proxy 0.7.6
Using redis-namespace 1.11.0
Using redlock 1.3.2
Using sprockets 3.7.2
Using net-http-persistent 4.0.2
Using sidekiq 6.5.9
Fetching puma 6.3.1
Using haml 6.1.1
Using hcaptcha 7.1.0
Using httplog 1.6.2
Using rdf 3.2.11
Using net-http 0.3.2
Using pastel 0.8.0
Using rqrcode 2.2.0
Using safety_net_attestation 0.4.0
Using webpush 0.3.8 from https://github.com/ClearlyClaire/webpush.git (at f14a4d5@f14a4d5)
Using tty-reader 0.9.0
Using tzinfo-data 1.2023.3
Fetching activesupport 7.0.7
Installing puma 6.3.1 with native extensions
Installing activesupport 7.0.7
Installing nokogiri 1.15.4 (x86_64-linux)
Using et-orbi 1.2.7
Fetching net-imap 0.3.7
Installing net-imap 0.3.7
Using net-pop 0.1.2
Using net-smtp 0.3.3
Fetching aws-sdk-core 3.180.3
Using faraday 1.10.3
Using cose 1.3.0
Using css_parser 1.14.0
Using domain_name 0.5.20190701
Fetching mime-types 3.5.0
Installing mime-types 3.5.0
Installing aws-sdk-core 3.180.3
Using llhttp-ffi 0.4.0
Using tpm-key_attestation 0.12.0
Using twitter-text 3.1.0
Using omniauth 2.1.1
Using sidekiq-bulk 0.2.0
Using sidekiq-unique-jobs 7.1.29
Using stoplight 3.0.1
Using json-ld 3.2.5
Using rdf-normalize 0.6.1
Using tty-prompt 0.23.1
Using globalid 1.1.0
Fetching activemodel 7.0.7
Installing activemodel 7.0.7
Using case_transform 0.2
Using json-jwt 1.15.3
Using nsa 0.2.8 from https://github.com/jhawthorn/nsa.git (at e020fcc@e020fcc)
Using swd 1.3.0
Using webfinger 1.2.0
Using pundit 2.3.0
Using simple-navigation 4.4.0
Using fugit 1.8.1
Using mail 2.8.1
Using faraday_middleware 1.2.0
Using elasticsearch-transport 7.13.3
Using http-cookie 1.0.5
Using premailer 1.21.0
Using fog-core 2.1.0
Using webauthn 3.0.0
Fetching activejob 7.0.7
Using json-ld-preloaded 3.2.2
Using rails-dom-testing 2.1.1
Using loofah 2.21.3
Using omniauth-cas 2.0.0 from https://github.com/stanhu/omniauth-cas.git (at 4211e6d@4211e6d)
Using ruby-saml 1.15.0
Using rack-oauth2 1.21.3
Using sanitize 6.0.2
Using azure-storage-common 2.0.4
Using elasticsearch 7.13.3
Using rufus-scheduler 3.9.1
Using fog-json 1.2.0
Using http 5.1.1
Fetching activerecord 7.0.7
Installing activejob 7.0.7
Using kt-paperclip 7.2.0
Using validate_email 0.1.6
Using validate_url 1.0.15
Using rails-html-sanitizer 1.6.0
Using azure-storage-blob 2.0.3
Using chewy 7.3.3
Using fog-openstack 0.3.10
Using omniauth-saml 2.1.0
Using sidekiq-scheduler 5.0.3
Using aws-sdk-kms 1.71.0
Using openid_connect 1.4.2
Fetching actionview 7.0.7
Using md-paperclip-azure 2.2.0
Using aws-sdk-s3 1.132.1
Using omniauth_openid_connect 0.6.1
Installing activerecord 7.0.7
Installing actionview 7.0.7
Fetching actionpack 7.0.7
Using kaminari-actionview 1.2.2
Using discard 1.2.1
Using kaminari-activerecord 1.2.2
Using strong_migrations 0.8.0
Using pghero 3.3.3
Using kaminari 1.2.2
Installing actionpack 7.0.7
Fetching actioncable 7.0.7
Fetching actionmailer 7.0.7
Fetching activestorage 7.0.7
Installing actionmailer 7.0.7
Installing actioncable 7.0.7
Using active_model_serializers 0.10.13
Fetching railties 7.0.7
Installing activestorage 7.0.7
Using omniauth-rails_csrf_protection 1.0.1
Using simple_form 5.2.0
Using sprockets-rails 3.4.2
Using premailer-rails 1.12.0
Fetching actionmailbox 7.0.7
Fetching actiontext 7.0.7
Installing railties 7.0.7
Installing actionmailbox 7.0.7
Installing actiontext 7.0.7
Using responders 3.1.0
Using doorkeeper 5.6.6
Using dotenv-rails 2.8.1
Using haml-rails 2.1.0
Using lograge 0.13.0
Using scenic 1.7.0
Using webpacker 5.4.4
Using rails-i18n 7.0.7
Using devise 4.9.2
Fetching rails 7.0.7
Using devise-two-factor 4.1.0
Installing rails 7.0.7
Using rails-settings-cached 0.6.6 from https://github.com/mastodon/rails-settings-cached.git (at v0.6.6-aliases-true@86328ef)
Bundle complete! 130 Gemfile dependencies, 242 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `./vendor/bundle
```
</details>

Command `yarn install`:

<details>
<summary>Long block of code</summary>

```
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^1.0.2 || 2 || 3 || 4"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
[4/6] Linking dependencies...
warning " > emoji-mart@3.0.1-j" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".
warning " > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning " > react-notification@6.8.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-swipeable-views@0.14.0" has incorrect peer dependency "react@^15.3.0 || ^16.0.0 || ^17.0.0".
warning "react-swipeable-views > react-swipeable-views-utils > react-event-listener@0.6.6" has incorrect peer dependency "react@^16.3.0".
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
$ husky install
husky - Git hooks installed
Done in 52.19s.
```
</details>

Another output from those commands `bundle exec rails assets:clean; bundle exec rails assets:clobber; bundle exec rails assets:precompile`:

<details>
<summary>Long block of code</summary>

```
I, [2023-08-22T11:38:03.857202 #7397]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
I, [2023-08-22T11:38:08.543858 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2023-08-22T11:38:08.544456 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2023-08-22T11:38:08.560656 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2023-08-22T11:38:08.560910 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2023-08-22T11:38:08.564287 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2023-08-22T11:38:08.897470 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js
I, [2023-08-22T11:38:08.897652 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js.gz
I, [2023-08-22T11:38:08.937833 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css
I, [2023-08-22T11:38:08.938026 #7449]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css.gz
Compiling...
Compiled all packs in /home/mastodon/live/public/packs
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/babel-plugin-lodash/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
```
</details>

If it is a dead end as I suppose it is, I'll just close the issue and reopen it only if the problem resurfaces. Sorry for any inconvenience.
