### ISSUE TITLE
Never apply hashtag autocompletion suggestions without positive confirmation

### ISSUE THREAD

**Issue by nemobis** [mastodon/mastodon#28653]
### Steps to reproduce the problem

1. Compose a new post or edit an existing one
2. Type something after a hashtag
3. ??
4. Try to go to the next word, for example by pressing a whitespace or punctuation key
5. ??
...

### Expected behaviour

What I typed should be preserved. Autocompletion suggestions should be applied only if I press Enter or Tab.

### Actual behaviour

What I typed gets replaced by whatever Mastodon thinks I must have meant for my hashtag, including case changes I don't want.

### Detailed description

I write in the Mastodon web UI and I sometimes have to type a hashtag half a dozen times because every single time I try to correct a typo or an incorrect case or whatever the UI pushes it back to the wrong version or to a totally random hashtag which happens to share some letters with what I typed.

When this happens, the only way to work around the bug is the following:
1. type what you meant to type
2. wait for the irrelevant suggestions to come up
3. press <kbd>ESC</kbd>
4. press a punctuation or space character
5. repeat (2)
6. press <kbd>ESC</kbd>
7. go on with your life

I somehow always fail to reproduce this bug when I try, but it's unescapable when I encounter it. It usually happens when I try to correct wrong toots posted on https://framapiaf.org/@wikimediaitalia through crossposting.

### Mastodon instance

framapiaf.org

### Mastodon version

v4.2

### Browser name and version

Firefox

### Operating system

Fedora Linux

### Technical details

This bug report is orthogonal to the various issues about *what* should be the first autocompletion suggestion.
* https://github.com/mastodon/mastodon/issues/9913
* https://github.com/mastodon/mastodon/issues/20267
* https://github.com/mastodon/mastodon/issues/27013

**Comment by nemobis** [comment]
Ok, I've just observed myself almost reproduce this bug a few times. What actually happens is that I press ctrl+Enter to post or shift+Enter to make a new paragraph, and I most definitely do not mean to confirm the autocompletion. Not sure whether that's what _always_ happens. But is there a way to not do that?

**Comment by Yekrats** [comment]
Yeah, there's a couple of things I noticed with hashtags where behavior is not ideal.

1. The hashtag list is sorted with all-lower-case first. So, if I am typing #Hash... then "#hash" will come up in the box at the top. The ideal behavior would be if the matching capitalization came to the top of the list first, then other matches.
2. Sometimes I type a hashtag, and then I click elsewhere in the composition window. I expect the hashtag drop-down to disappear, but it keeps focus even though my cursor moves to a completely different place. So, if I press enter, it selects the wrong hashtag. Ideal behavior would be to remove the hashtag-dropdown-list if focus is moved away from the hashtag that is currently being typed. (This ideal change of focus behavior is what happens in the Github window that I'm typing in right now.)

**Comment by Yekrats** [comment]
The problem probably stems from here: app/javascript/mastodon/components/autosuggest_textarea.jsx

**Comment by nemobis** [comment]
I just observed another cause of this issue: the hashtag suggestions never go away even if you move your cursor. For example, in this post, I added the hashtag, then the colon, then I used my mouse to go to the previous sentence and add a newline, but first I had to press <kbd>ESC</kbd> to dismiss the hashtag suggestion, which never went away.
![Screenshot_20240118_102923](https://github.com/mastodon/mastodon/assets/901528/0e9cf8d0-686b-435a-ae0c-1ecd6e2f15b5)

**Comment by nemobis** [comment]
I found another case where the hashtag suggestion is applied against my will: using ctrl-End. Here I add a comma after an existing hashtag, go to the end of the line with ctrl-end and press enter to get a newline, but instead the hashtag gets confirmed and the comma removed (!) even if it's nowhere near the cursor.

Probably it would help to dismiss the hashtag suggestions when the user types characters which are not among the allowed ones for hashtags, like punctuation.

[simplescreenrecorder-2024-03-08_08.58.59.webm](https://github.com/mastodon/mastodon/assets/901528/ef83f0fb-44c0-4f7d-ac78-729dcf1998a3)

**Comment by nemobis** [comment]
Another issue I encounter is that the suggested hashtag often appears out of screen, due to the very long and narrow composing window:
![Screenshot_20240603_172125](https://github.com/mastodon/mastodon/assets/901528/75deb231-e981-4bbd-809d-fd519e216cdc)

Significant scrolling would be required to notice it:
![Screenshot_20240603_172236](https://github.com/mastodon/mastodon/assets/901528/4a1cde4b-8044-4b9c-86b8-230047a03a39)

**Comment by FediVideos** [comment]
This was a bug on all versions of Mastodon a while ago, but it was fixed?

I cannot reproduce this bug on the current release version of vanilla Mastodon (see the screenshots), but framapiaf.org runs on a customised version of Mastodon so perhaps this has somehow caused the behaviour you are seeing on your instance?

Screenshots below show the behaviour on a vanilla Mastodon instance when clicking on the suggestion. The cases I used when typing are preserved, the cases of the suggestion are ignored.

![Screenshot from 2024-09-16 11-51-07](https://github.com/user-attachments/assets/f13169fb-e1cf-4dbf-b6d9-3ebd010593dd)
![Screenshot from 2024-09-16 11-51-18](https://github.com/user-attachments/assets/da513c69-ef77-4759-a927-f881360bea7c)

**Comment by nemobis** [comment]
@FediVideos Thanks for attempting to reproduce. Which version have you tried this on? I confirm it still happens on v4.2.12 (multiple instances, not just framapiaf). Casing differences are not the only problem: the suggestion could also be an autocompletion that you don't need, a suggestion of something completely different, or the same suggestion repeated again after adding punctuation.

**Comment by FediVideos** [comment]
Had a discussion with someone in a thread on Mastodon (at https://mastodon.social/@hallenbeck/113136886435827499) and issue seems to be that some people write the hashtag all the way through while others just write it partially and then click on the suggestion.

If you write it all the way through, then your capitalisation should be preserved just like in the screenshots. If you only write it partially and then click on a suggestion, it will use the suggestion's capitalisation.

Changing the suggestions is difficult as sometimes the same string can be split differently (#SuperBowl and #SuperbOwl for example) so perhaps the suggestions need to show multiple versions of the same string with different capitalisations. The danger is that some people might write mistakes (like #SuperBOwl) which no one wants, so perhaps the multiple versions should just be the most popular variations on that server.

**Comment by nemobis** [comment]
Clicking the suggestion is an uncontroversial case. The question is, does anyone rely on the current behaviour of overriding what you typed with an enter or ctrl-enter, especially after adding punctuation or spaces or moving the cursors elsewhere?

**Comment by nemobis** [comment]
It sounds like, in v4.3.5, https://github.com/mastodon/mastodon/pull/34070 will at least work around one of the most annoying effects of this issue (overriding my spelling of the hashtag).
