### ISSUE TITLE
Wrong link on a preview card

### ISSUE THREAD

**Issue by last-partizan** [mastodon/mastodon#29386]
### Steps to reproduce the problem

This happens when you post a link to a page with redirect (for example, protected by captcha), this is an example:

- Page: https://social.lansky.name/@hn100/111987130991989746
- API: https://social.lansky.name/api/v1/statuses/111987130991989746

### Expected behaviour

Link on a card is the same as link in a post

### Actual behaviour

Link on a card is different (captcha site with redirect to a link in this case)

### Detailed description

Relevant part of the response:

```json
{
  "id": "111987130991989746",
  "content": "\u003cp\u003eEveryone seems to forget why GNOME and GNOME 3 and Unity happened (2022)\u003c/p\u003e\u003cp\u003eLink: \u003ca href=\"https://liam-on-linux.dreamwidth.org/85359.html\" target=\"_blank\" rel=\"nofollow noopener noreferrer\" translate=\"no\"\u003e\u003cspan class=\"invisible\"\u003ehttps://\u003c/span\u003e\u003cspan class=\"ellipsis\"\u003eliam-on-linux.dreamwidth.org/8\u003c/span\u003e\u003cspan class=\"invisible\"\u003e5359.html\u003c/span\u003e\u003c/a\u003e\u003cbr /\u003eDiscussion: \u003ca href=\"https://news.ycombinator.com/item?id=39490879\" target=\"_blank\" rel=\"nofollow noopener noreferrer\" translate=\"no\"\u003e\u003cspan class=\"invisible\"\u003ehttps://\u003c/span\u003e\u003cspan class=\"ellipsis\"\u003enews.ycombinator.com/item?id=3\u003c/span\u003e\u003cspan class=\"invisible\"\u003e9490879\u003c/span\u003e\u003c/a\u003e\u003c/p\u003e",
  "card": {
    "url": "https://www.dreamwidth.org/captcha?returnto=https://liam-on-linux.dreamwidth.org/85359.html",
    "title": "Captcha Check"
  }
}
```

If i understood this correctly, mastodon tries to resolve the URL, receives redirect, and uses redirect target instead of original link for the card.

### Mastodon instance

social.lansky.name

### Mastodon version

v4.2.8

**Comment by chabala** [comment]
This affects me as well, e.g.: https://fosstodon.org/@chabala/112038918632334324
I linked to: https://github.com/pages-themes/minimal/pulls
preview card linked to: https://github.com/pages-themes/minimal
result: 75% of the screen real estate of the toot is going to the wrong URL

**Comment by nicdex** [comment]
Please be careful when/if fixing this. Take into consideration the potential hacking of links, that currently affect Twitter/X as explained in this blog post https://lifehacker.com/tech/its-not-safe-to-click-links-on-x

**Comment by c960657** [comment]
This was fixed in #27312 (not yet included in an official release).

**Comment by kytta** [comment]
> This was fixed in #27312 (not yet included in an official release).

Wait, what? The PR is almost one year old by now, how on Earth hadn't it been released yet?

**Comment by mprove** [comment]
The problem is still confusing the users and bothering me. [Example](https://norden.social/@chronohh/113253472006802775)
