### ISSUE TITLE
`Your application is pending review by our staff. ~` prevents the development web app from working.

### ISSUE THREAD

**Issue by taichi221228** [mastodon/mastodon#29873]
### Steps to reproduce the problem

1. Repo fork
2. Create Dev Containers
3. Run `foreman start`
4. Sign in as `admin@localhost`

### Expected behaviour

The development web app works

### Actual behaviour

I can't navigate away from `http://localhost:3000/auth/edit` because `Your application is pending review by our staff. ~`

### Detailed description

<img width="2000" alt="image" src="https://github.com/mastodon/mastodon/assets/58300794/ed8e5aca-1cbd-46fb-8497-65875bc8f7c4">

### Mastodon instance

I don't know. What is the instance of your development environment?

### Mastodon version

v4.3.0-alpha.3

### Browser name and version

Google Chrome 123.0.6312.107

### Operating system

macOS Sonoma 14.4.1

**Comment by renchap** [comment]
This is weird, it should have been fixed in `main`.

Are you able to manually approve the account through the CLI, with `RAILS_ENV=production bin/tootctl accounts modify <username> --approve` ?

**Comment by taichi221228** [comment]
Thank you for your reply.

When I entered that, the following output was obtained.

```console
vscode@8e679771384e:/workspaces/mastodon$ RAILS_ENV=production bin/tootctl accounts modify admin@localhost --approve
/workspaces/mastodon/config/environments/production.rb:160:in `fetch': key not found: "OTP_SECRET" (KeyError)
        from /workspaces/mastodon/config/environments/production.rb:160:in `block in <main>'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/railtie.rb:257:in `instance_eval'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/railtie.rb:257:in `configure'
        from /workspaces/mastodon/config/environments/production.rb:5:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/engine.rb:568:in `block (2 levels) in <class:Engine>'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/engine.rb:567:in `each'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/engine.rb:567:in `block in <class:Engine>'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:50:in `each'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /workspaces/mastodon/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/application.rb:426:in `initialize!'
        from /workspaces/mastodon/config/environment.rb:7:in `<main>'
        from /workspaces/mastodon/lib/mastodon/cli/base.rb:4:in `require_relative'
        from /workspaces/mastodon/lib/mastodon/cli/base.rb:4:in `<main>'
        from /workspaces/mastodon/lib/mastodon/cli/main.rb:3:in `require_relative'
        from /workspaces/mastodon/lib/mastodon/cli/main.rb:3:in `<main>'
        from bin/tootctl:5:in `require_relative'
        from bin/tootctl:5:in `<main>'
vscode@8e679771384e:/workspaces/mastodon$ 
```

I'm not familiar with Ruby, so I don't know, but it seems that the error is occurring in `config.x.otp_secret = ENV.fetch('OTP_SECRET')` in `production.rb`.

When I submitted a PR to this Repo before, I think I was able to just fork and start up Dev Containers without any problems, but is there anything else I need to do?

**Comment by phocks** [comment]
Yeah this is still happening for me in main too. Just set up a dev environment and tried to log in with admin@localhost and mastodonadmin and I get the exact same message. Tried changing password and email.

**Comment by phocks** [comment]
This fixed it for me: `RAILS_ENV=development bin/tootctl accounts modify admin --approve` 

Note: the RAILS_ENV=development vs RAILS_ENV=production
