### ISSUE TITLE
Hover cards appear for touchscreen touches

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#32685]
### Steps to reproduce the problem

1. Touch your finger on a UI element that has a hover card in a way that doesn’t trigger its interaction (for example, long press a username to bring up the browser context menu, then close the context menu)

### Expected behaviour

Hover card shouldn’t appear for touches

### Actual behaviour

Hover card appears and remains stuck on screen until you touch some other UI element, which performs some action you didn’t expect on *that* element

### Mastodon instance

mastodon.online

### Mastodon version

v4.3.1

### Browser name and version

Safari

### Operating system

iPadOS 18.2b1

### Technical details

It looks like it’s using `mouseenter` and `mouseleave` events, which fire for any pointing device, not just a mouse. It could probably instead use something like pointer events and check that the pointer type is actually a mouse or pen that could conceivably support hover.

**Comment by ClearlyClaire** [comment]
Using `pointerenter` and `pointerleave` and checking `pointerType` looks like a decent way to achieve this, but I'm not an expert in this area, and I couldn't find a set of best practices around that.

**Comment by chr-1x** [comment]
Went looking for an issue about this because it's really been bothering me. I'm constantly getting hover popups on mastodon when using iOS web browsers. I've accidentally unfollowed multiple people because the hover modal shows up and puts an unfollow button right where i was about to tap. This is a huge UX papercut on the mobile web interface.

**Comment by daprice** [comment]
I’m not sure if a recent change is causing this or what, but I’ve been running into this a lot more recently as well, in more situations than just what I mentioned in the original issue. Pretty much any time I tap on any kind of overlapping element (like a search suggestion), the interface treats it as if I have a pretend mouse cursor permanently hovering in the spot where I tapped, so it inevitably brings up a hover card that I have no way of dismissing.

Now that I try it some more, I can’t manage to tap a search suggestion or recent search *without* ending up blocked by a permanent hover card, making the search interface on the web effectively unusable on my phone.

I’d attach a screen recording except Github keeps saying it “failed to upload”, but here are some updated steps that trigger it every time for me in iOS 26.3 Safari:
1. Tap the magnifying glass Search icon in the bottom nav
2. Tap the search field to focus it
3. Tap one of the recent searches in the recent searches overlay

Expected result: It performs the search.
Actual result: It performs the search, and if there are any results, a hover card appears at the location you tapped in step 3. The hover card seemingly cannot be dismissed using touch.

**Comment by diondiondion** [comment]
@daprice We've just merged a potential fix for this and you should be able to test this tomorrow on mastodon.online. 

(I don't have a mobile Apple device so I had to make do with the iOS Simulator on my Mac where I wasn't able to exactly reproduce the issue following your steps above, so feel free to let me know if the card still pops up anywhere.)

**Comment by daprice** [comment]
@diondiondion assuming the attempted fix is in v4.6.0-nightly.2026-03-04, it did fix it for the scenario in my original report but it did not fix it for the one I recently found on the search page.

Github is still failing to upload the screen recording so here’s an iCloud version: https://share.icloud.com/photos/063GJ77cKVloWZN_9637kumsQ

**Comment by daprice** [comment]
FWIW, I can repro this in the iOS 26.2 simulator, but it seems to depend on whether the search suggestion I tap happens to line up with a profile in the search results, which depending on screen size and font size could be the second or third “recent search”.

**Comment by diondiondion** [comment]
> FWIW, I can repro this in the iOS 26.2 simulator, but it seems to depend on whether the search suggestion I tap happens to line up with a profile in the search results, which depending on screen size and font size could be the second or third “recent search”.

Thanks for checking! 🙏  I'll give this another go.

**Comment by diondiondion** [comment]
I just put up a PR with a new fix, thanks again for the pointers @daprice! I was able to reproduce this issue even in a regular desktop browser with mouse usage, and I think the fix should be much more robust now.
