### ISSUE TITLE
Expanding search results stops early

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#33427]
### Steps to reproduce the problem

1. Search for some term in the Mastodon Web interface
2. Load past the initial results
3. Continue scrolling/loading more

### Expected behaviour

All results should be returned eventually

### Actual behaviour

The interface stops offering to load more results before they have all been returned

### Detailed description

This is caused by the `hasMore` logic in `app/javascript/mastodon/features/status/index.jsx` relying on the number of results being equal to 1 modulo 10.

This logic is really brittle, and in particular will always break after a few pages because we expand new results by 11 new items, not 10.

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-12-18

### Browser name and version

Firefox 133

### Operating system

Linux

**Comment by horaceyoung** [comment]
Is there any need to update the search index. I've merged this change for my instance but still having search results stopping early at the 10th post.

**Comment by ClearlyClaire** [comment]
There is no need to rebuild search indexes, the issue discussed here (and partially addressed by #33428) is purely a front-end issue.

In your case, I would double-check that assets have been rebuilt and `mastodon-web` then restarted.

**Comment by Diwannist** [comment]
We might also have this issue and it may be limiting the effectiveness of the network dramatically; as one of the most valuable parts of the network might be its repository; and that may be rendered less useful if we can't search it. We believe we might gain way more (especially niche) knowledge and grow our network substantially if this were not an issue.

https://github.com/user-attachments/assets/5f49842b-ffd4-4a94-b341-a5727c95c38f

**Comment by ClearlyClaire** [comment]
Yes, this is a known issue that requires some changes to our search code and that we will try to address in Mastodon v4.6.
