### ISSUE TITLE
Images in CloudFlare R2 with ECH do not show

### ISSUE THREAD

**Issue by ikke-t** [mastodon/mastodon#33640]
### Steps to reproduce the problem

1. Use recent Firefox
2. Open mastodon site https://mementomori.social
3. see how images do not show

### Expected behaviour

Images show  up

### Actual behaviour

Images do not show up

### Detailed description

In developer view in Firefox, on console you can see errors like this, lots of them. Each picture generates one:

```
Failed to load ‘https://media.mementomori.social/cache/preview_cards/images/010/158/459/original/5a6021597767fd77.jpg’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘Error: no-response :: [{"url":"https://media.mementomori.social/cache/preview_cards/images/010/158/459/original/5a6021597767fd77.jpg","error":{}}]’. sw.js:1:78075
```

If you go directly to such URL, FF gives this error:

![Image](https://github.com/user-attachments/assets/9456ef81-b335-4aa5-9433-1c368af0bf7b)

Looking from wireshark it is seen that where curl, chromium and other browsers go to that url directly, but Firefox tries to go after encrypted request using [Encrypted Client Hello (ECH)](https://developers.cloudflare.com/ssl/edge-certificates/ech/#enable-ech). That is the protocol that sends encrypted request for web page, having SNI header which is seen by host which forwards the request to right content.

So R2 has an advanced feature, which doesn't quite work with mastodon.  

The only way to get around this using Firefox is to disable ECH from Firefox. It can be done from about:config setting this variable to "true": network.dns.echconfig.fallback_to_origin_when_all_failed

This happens on my Fedora 41 linux FF firefox-134.0-1.fc41.x86_64, as well as on my android phone and tablet with their latest firefoxes. Also some other users reported the same.

### Mastodon instance

mementomori.social

### Mastodon version

v4.4.0-alpha.1

### Browser name and version

Firefox 134

### Operating system

Fedora Silverblue 41, Android 15

**Comment by ronilaukkarinen** [comment]
I could reproduce this with older Firefox, but as soon as I updated my Firefox to 134.0.1 (64-bit) on macOS Sequoia (15.2) or Pop!_OS (Ubuntu 22.0.4 LTS jammy variant) the problem disappeared.

Can Mastodon core service worker be improved to take account Firefox and ECH better?

**Comment by ronilaukkarinen** [comment]
Other piece of information, we have `S3_DISABLE_CHECKSUM_MODE=true` as instructed [here](https://github.com/mastodon/mastodon/issues/26469#issuecomment-1676802435). Is this relevant? Just fishing.

**Comment by saaste** [comment]
I have the same problem on Android, Firefox 134.0.1. I couldn't reproduce the problem on MacOS Sequoia 15.1.1.

**Comment by d2s** [comment]
Same problem visible with Firefox 134.0.1 version on a Windows 11 computer.
When viewing the Mastodon instance with Cache disabled (by using Firefox Developer Console), all of the images are missing.

Also getting NS_ERROR_INTERCEPTION_FAILED error messages on the Firefox Developer Console that could be related to Service Workers, according to a quick search from elsewhere.

![Image](https://github.com/user-attachments/assets/b847e9bf-fccf-4470-bb51-b510aafff4e7)

Example of what a post looks with missing images:

![Image](https://github.com/user-attachments/assets/1de3bd14-38c9-4309-a5e2-dc0ec6dc0386)

**Comment by smoltron** [comment]
134.0.1 and Arch linux - images and media are not shown

**Comment by ronilaukkarinen** [comment]
We just updated to today's alpha, v4.4.0-alpha.2, commit [4bd969e](https://github.com/mastodon/mastodon/commit/4bd969e4bb54297981d385903bf8a4348b394f09), the problem did not go away - although I personally still can't reproduce this with my browsers. Also not seen on Firefox on iOS 18, but I guess that's webkit anyway.

**Comment by d2s** [comment]
For me, it works again on multiple devices. Probably something was fixed somewhere, but I don't know where. 😅

**Comment by nenunen** [comment]
I had this problem yesterday on Android 14, but everything seems to work again at the moment. On Fedora 40 the problem persists. Firefox 134.0.1 on both.

**Comment by shleeable** [comment]
@ronilaukkarinen in the past, I've had this problem and it was related to the service worker which is cached by the nginx
it might also cause problems if you've changed the URL/domain for the media which changed the CSP.... 

so clear the nginx cache if you're using it. `/var/nginx/cache/`

**Comment by ikke-t** [comment]
The first thing I tried was to do exactly that. I emptied the cache, and restarted nginx. Also browser cache was cleared.

**Comment by nenunen** [comment]
I can reproduce the problem reliably on Fedora 40 in newly created Firefox profiles (`firefox --ProfileManager`) by disabling “Allow Firefox to install and run studies” in the preferences or by removing the study “Encrypted Client Hello - Fallback Mechanism” from the Active studies list. Its full description:

> This experiment enables a fallback mechanism for Encrypted Client Hello. This feature maximizes compatibility with websites that have misconfigured or unexpected DNS configurations.

**Comment by renchap** [comment]
I do not think this is related to Mastodon itself, it seems to be an issue on the media.mementomori.social side? The error is between the browser and this domain, and it does not hit any Mastodon code in this path?

**Comment by ikke-t** [comment]
or is the mastodon code in browser directly connecting to CloudFlare R2 image cache? R2 is used as image storage here. TCPdump shows firefox tries to connect to R2 ECH address directly.

**Comment by ronilaukkarinen** [comment]
My Mac Firefox (134.0.1 (aarch64)) shows this in [Browsing Experience Security Check](https://www.cloudflare.com/en-gb/ssl/encrypted-sni):

![Image](https://github.com/user-attachments/assets/2d2090c2-645f-4231-a0a6-54c59d3bfdb1)

The bottom of the Cloudflare page says:

> ECH is not yet widely available for web services behind Cloudflare, but we are working closely with browser vendors on the implementation and deployment of this important privacy enhancement for TLS.

Then again on [ECH Protocol (beta)](https://developers.cloudflare.com/ssl/edge-certificates/ech/) page:

> ECH is enabled by default on Free zones.

Currently on my Mac Firefox the images work fine and haven't been able to reproduce this issue on other systems either regardless of settings.

ECH has been enabled enabled in Firefox by default since 119 which was released on October 24, 2023, but we didn't get reports about this issue until recently. So it cannot be purely between Firefox and Cloudflare, can it?

Has there been changes in Mastodon core about service worker or something related to this? How can we make sure?

**Comment by ypcs** [comment]
Relates somehow to issues with Encrypted Client Hello setup: at least on my setup toggling Firefox value `network.dns.echconfig.enabled` from true (default) to false seems to fix issue. Tested with asset https://media.mementomori.social/cache/media_attachments/files/113/861/538/705/401/310/original/369c42fe8a6c21ec.png .

```
$ dig media.mementomori.social https

; <<>> DiG 9.XXX <<>> media.mementomori.social https
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57749
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;media.mementomori.social.	IN	HTTPS

;; ANSWER SECTION:
media.mementomori.social. 34	IN	HTTPS	1 . alpn="h2" ipv4hint=104.21.16.1,104.21.32.1,104.21.48.1,104.21.64.1,104.21.80.1,104.21.96.1,104.21.112.1 ech=AEX+DQBB7gAgACDp3QRUR3J0v4R/WVE8nBmMT/BvRM2VLNjugcyEO/OeCQAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA= ipv6hint=2606:4700:3030::6815:1001,2606:4700:3030::6815:2001,2606:4700:3030::6815:3001,2606:4700:3030::6815:4001,2606:4700:3030::6815:5001,2606:4700:3030::6815:6001,2606:4700:3030::6815:7001

;; Query time: 19 msec
;; SERVER: XX.XX.XX.XX (UDP)
;; WHEN: Mon Jan 20 21:18:49 EET 2025
;; MSG SIZE  rcvd: 298
```

Would eg. https://developers.cloudflare.com/ssl/edge-certificates/ech/#enable-ech help, ie. if you try to disable it temporarily?

Anyways, not going to debug further, hopefully this helps.

Related: https://wiki.mozilla.org/Security/Encrypted_Client_Hello
Related: https://blog.cloudflare.com/encrypted-client-hello/

**Comment by ronilaukkarinen** [comment]
I finally was able to reproduce this on my Linux machine. On Windows and Mac it doesn't get reproduced with any setting.

![Image](https://github.com/user-attachments/assets/7c01ad96-234b-4087-b80b-04b3873c5487)

But I needed to set this `about:config` setting false, it was true for some reason:

```bash
network.dns.echconfig.fallback_to_origin_when_all_failed
```

The images itself work fine and certs should be fine, like they have been for the past 2 years.

So, now that I got this reproduced on Linux version of Firefox 134.0.1 (64-bit), I moved on to tweak Clouflare settings. The things I tried:

* **SSL/TLS → Overview → Configure → Flexible** (Full (Strict) by default). Then restarted Firefox and emptied cache. Did nothing.
* **Speed → Optimization → Protocol Optimization → HTTP/3 (with QUIC) → Disabled. Then restarted Firefox and emptied cache. This did  the trick!

![Image](https://github.com/user-attachments/assets/d55e0aa2-b05b-425b-a11c-88e2e78faa30)

I also got reproduced this in my local environment and there also first didn't work, then worked after disabling HTTP/3. If this would have not worked I would have next looked at entry.js / sw.js.

@ikke-t also confirmed working.

If this was the fix, this issue can be closed. Waiting for confirmation from more users. It seems this wasn't a Mastodon issue after all. I just wonder why it popped up now when things been working great since 2022.

**Comment by ronilaukkarinen** [comment]
> Would eg. https://developers.cloudflare.com/ssl/edge-certificates/ech/#enable-ech help, ie. if you try to disable it temporarily?

There is no way to disable it, the setting is not there any more, like stated ECH is enabled by default. However, it seems HTTP/3 setting contains it so disabling HTTP/3 might be the one that solves this. For me it did at least.

**Comment by ronilaukkarinen** [comment]
Hmm, I'm really not sure if it's fixed this way. This is a stranger to me.

Now I noticed why they get fixed for me, every time I restart Firefox my `network.dns.echconfig.fallback_to_origin_when_all_failed` is set to `true`. I don't know why. Because that flag fixes it.

This is so weird.

**Comment by ikke-t** [comment]
Would you happen to have the option to se d stats to mozilla on? As discussed today in mastodon, it turns the setting to true.

**Comment by ikke-t** [comment]
Explained here in Finnish: https://mementomori.social/@nen/113859642032542456

**Comment by ronilaukkarinen** [comment]
> Would you happen to have the option to se d stats to mozilla on? As discussed today in mastodon, it turns the setting to true.

Oh yeah, right. So in short, this issue affects all users who have specifically selected Studies to be disabled here:

![Image](https://github.com/user-attachments/assets/a1160c6f-f779-40aa-bacb-5b47f55536c1)

Studies are enabled by default.

I guess not much or anything can be done from Mastodon's software side about this, since this is a server side issue, because the image itself cannot be loaded up when browser can't open the image at all, e.g. https://media.mementomori.social/cache/custom_emojis/images/000/001/110/original/86884e5e9ad4c1fd.png

I think I'm going to try and generate my own cert next via Let's Encrypt.

**Comment by ronilaukkarinen** [comment]
![Image](https://github.com/user-attachments/assets/58776cc4-7638-494f-8220-8abdf56643f5)

Had to purchase Pro to see this, this was disabled. Got a hint [here](https://www.answeroverflow.com/m/1304797007109685348).

I enabled the setting, but don't yet see images. Also purged cache. Perhaps later we'll see if it works.

**Comment by saaste** [comment]
> I enabled the setting, but don't yet see images. Also purged cache. Perhaps later we'll see if it works.

I just tried this on my Android phone. Still broken images.

Then I enabled studies, and after Firefox restarted, the images are visible again. I will leave it on for now just to see if the images break again.

**Comment by ikke-t** [comment]
I need to learn how to analyze this. It I also now played around with tcpdump and wireshark. Looking at the mementomori page being loaded via android ff on tablet shows clearly it goes for http3 ech (cloudflare-ech.com):

![Image](https://github.com/user-attachments/assets/c0362733-ce38-4bad-ae17-aabc58182761)

where as the same page accessed via chrome on the same tablet goes for http2 (media.mementomori.social:

![Image](https://github.com/user-attachments/assets/32bf9aa0-386f-4c11-818c-094af5a10d71)

So question is, what makes FF only go for http3 ech? Is the hint given in mastodon code, or how does it realize this is http3? And why only FF gets directed there?

And eventually then, why wont the ech work on R2?

**Comment by ronilaukkarinen** [comment]
> And eventually then, why wont the ech work on R2?

This is a mystery. Both ECH and HTTP/3 are enabled.

**Comment by ikke-t** [comment]
Yes, I verified in matrix already my firefox on Fedora SilverBlue, android tablet and android phone works just fine. The R2 service operates now using HTTP/2 instead of HTTP/3, so the ECH feature is off, and firefox connects OK to pictures in cache.

Before the change the media.mementomori.social resolved with ECH info:

```
$ dig HTTPS media.mementomori.social

; <<>> DiG 9.18.30 <<>> HTTPS media.mementomori.social
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41131
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;media.mementomori.social.      IN      HTTPS

;; ANSWER SECTION:
media.mementomori.social. 300   IN      HTTPS   1 . alpn="h3,h2" ipv4hint=104.26.8.127,104.26.9.127,172.67.73.115 ech=AEX+DQBBGAAgACCLQII1u27goycagBjWrVZKDRYKaR4MXpcYocy5PIZbWQAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA= ipv6hint=2606:4700:20::681a:87f,2606:4700:20::681a:97f,2606:4700:20::ac43:4973

;; Query time: 9 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Jan 21 22:16:46 EET 2025
;; MSG SIZE  rcvd: 221
```

and after the change the DNS does not advertice it as ECH service any longer:

```
$ dig HTTPS media.mementomori.social

; <<>> DiG 9.18.30 <<>> HTTPS media.mementomori.social
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24870
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;media.mementomori.social.      IN      HTTPS

;; ANSWER SECTION:
media.mementomori.social. 300   IN      HTTPS   1 . alpn="h2" ipv4hint=104.26.8.127,104.26.9.127,172.67.73.115 ipv6hint=2606:4700:20::681a:87f,2606:4700:20::681a:97f,2606:4700:20::ac43:4973

;; Query time: 8 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Jan 21 22:42:09 EET 2025
;; MSG SIZE  rcvd: 143
```

So, the ECH is verified to be off, and problem is gone.

**Comment by schnz** [comment]
I am not using mastadon, but found this issue because I experience the same problem in Firefox 135.0 when trying to access Cloudflare R2 buckets via custom domain.

@ronilaukkarinen already posted the solution - namely to disable ECH:

> **Disabled:** Encrypted Client Hello (ECH)

However, for users that use the free Cloudflare plan, this setting isn't visible in the Dashboard. I found this blog post here that also provides the ability to disable the setting via API call: https://neonode.cc/en/blog/how_to_disable_ech_cf/

```sh
curl -X PATCH "https://api.cloudflare.com/client/v4/zones/{ID_ZONE}/settings/ech" \
    -H "X-Auth-Email: {ACCOUNT_EMAIL}" \
    -H "X-Auth-Key: {GLOBAL_API_KEY}" \
    -H "Content-Type:application/json" \
    --data '{"id":"ech","value":"off"}'
```

This worked for me and I am now able to access my R2 custom domain via Firefox again.

**Comment by FolcaHub** [comment]
I'm not sure if can help, but setting **network.dns.echconfig.fallback_to_origin_when_all_failed**  to **true**  but also **turning off and on my vpn**, fixed the problem for me.
