### ISSUE TITLE
5 Pending hashtags, but there's nothing there

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#34785]
### Steps to reproduce the problem

I do not know what caused this.

Visit `/admin/trends/tags?status=pending_review` on your instance

### Expected behaviour

Either 0 pending hashtags or 5 hashtags listed

### Actual behaviour

5 pending hashtags but 0 hashtags listed

### Detailed description

![Image](https://github.com/user-attachments/assets/a4d5c655-8427-4526-9148-966e7de3ff57)

I noticed this a while after upgrading my server to the git main.

### Mastodon instance

https://ailbhean.co-shaoghal.net

### Mastodon version

4e2aa78a561c2f81ac6fe86c3e32c656f87572d9

### Browser name and version

Firefox 138.0.4

### Operating system

Linux Mint 21.3 (Client), Debian 12 Bookworm (Server)

**Comment by wolfspyre** [comment]
This happens to me too. 

I suspect it's related to 'posts that are one-degree-away' from this server context ... ie the 'trending' entities have attributes, and the list of attributes which need moderation are relevant to those posts ... and the hashtags ets that corespond to them... 

however the 'reviewed/unreviewed/pending/approved' apply to all content the server is peripherally aware of (incl hashtags which no user of this server have seen/used directly ....


Q: is my understanding of the difference correct? 


assuming so .... the disconnect is a bit odd... because as an administrator, (even for a tiny instance with only a few users)  having a thing that says I have a bunch of stuff to review is a little anxiety inducing ..... mine shows > 1000 hashtags that are pending .... and yet doing so requires opening each in a popup, and then manually approving them.... admittedly, this only takes tens of second each ... but ..... with thousands of tags to do that for ... it's a bit unreasonable ...


How can this experience be improved? 

ideally, there'd be a better way to address this:

![Image](https://github.com/user-attachments/assets/96a18dfb-fe3c-466e-bb88-98b048ea19a7)




![Image](https://github.com/user-attachments/assets/e74287f3-c0d9-4ad7-98cd-aa127c14a293)

**Comment by WelshPixie** [comment]
![Image](https://github.com/user-attachments/assets/af3aefcb-8d57-4aa1-b875-49a0ead8a277)
![Image](https://github.com/user-attachments/assets/f6b430e8-2122-4790-a0f5-7e410f248292)
![Image](https://github.com/user-attachments/assets/327fc412-d31f-4f24-ab0c-a232897e2787)

Edit: I've figured out what they are; if I edit and save the 'review requested' hashtags, the count on the admin panel drops accordingly. 

Seem to be getting this issue today on mastodon.art. Usually there aren't more than ten or so pending trending hashtags per day. After I approve or reject them, the 'pending hashtags' count on the admin panel drops to 0. Today, unusually, I had some 140 trending tags to approve from overnight, and after going through them all, the count on the admin panel is stuck on 42.

When going to moderation > hashtags I can see that there are pending tags. If I open one of these and save the settings, that tag will no longer be marked as pending, but the count on the admin panel doesn't decrease - it stays at 42 (I'm guessing because pending hashtags and pending *trending* hashtags aren't connected).

**Comment by ThisIsMissEm** [comment]
@mjankowski could this be related to your changes here? https://github.com/mastodon/mastodon/pull/35120

**Comment by mjankowski** [comment]
> [@mjankowski](https://github.com/mjankowski) could this be related to your changes here? [#35120](https://github.com/mastodon/mastodon/pull/35120)

Yes, this seems like a dupe of https://github.com/mastodon/mastodon/issues/35085 which was fixed by that.

**Comment by ThisIsMissEm** [comment]
@mjankowski someone was telling me they still see this behavior on latest 4.4, but I don't have more details

**Comment by brendankinney** [comment]
I'm experiencing the same issue. I'm hosting an instance on Masto.host and am seeing a discrepancy between the administration panel and hashtag moderation panel:

> <img width="596" height="323" alt="Image" src="https://github.com/user-attachments/assets/47404648-f7e0-46a9-b207-671fca92a800" />

As you can see, the panel above shows 165 pending hashtags.

When I go into the hashtag approval panel, there's nothing to approve.

> <img width="703" height="292" alt="Image" src="https://github.com/user-attachments/assets/4e0a0a43-361b-4243-88ad-090820a5be15" />

**Comment by mjankowski** [comment]
Thank you for those screenshots - I think I see the issue now. I had not previously appreciated the issue was on the admin dashboard as well, and I assumed people were talking only about the trending tags page (which used to have this issue, but should be fixed now ... contingent on server software version, etc).

Linked PR should resolve.
